// ============================================================
// Список слов тренажёра английского. Источник истины после разового
// импорта из ~/handbook/english-words.csv (вне репозитория, не коммитится).
// Правь этот файл напрямую — id, word, translation, example, note, kind, source, ngslRank.
// ============================================================

export type WordKind = 'it' | 'general'

export interface EnglishWord {
  id: string
  word: string
  translation: string
  example: string
  /** заметка к слову (ложный друг, множественное число и т.п.) — может быть пустой строкой */
  note: string
  kind: WordKind
  /** источник, из которого взято слово (например «git», «отчёт агента») */
  source: string
  /** ранг в NGSL (New General Service List), если известен */
  ngslRank: number | null
}

export const englishWords: EnglishWord[] = [
  {
    id: 'verify',
    word: 'verify',
    translation: 'проверять, подтверждать',
    example: 'Verified independently: files exist.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'independently',
    word: 'independently',
    translation: 'независимо, самостоятельно',
    example: 'Verified independently: files exist.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 1006,
  },
  {
    id: 'intended',
    word: 'intended',
    translation: 'задуманный, намеченный',
    example: 'Git shows only the intended changes.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 1114,
  },
  {
    id: 'reconciliation',
    word: 'reconciliation',
    translation: 'сверка',
    example: 'Count reconciliation: exact match on all 16 categories.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'exact',
    word: 'exact',
    translation: 'точный',
    example: 'Exact match on all 16 categories.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 2327,
  },
  {
    id: 'match',
    word: 'match',
    translation: 'совпадение; совпадать',
    example: 'Exact match on all 16 categories.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 850,
  },
  {
    id: 'discrepancy',
    word: 'discrepancy',
    translation: 'расхождение, несоответствие',
    example: 'No discrepancies.',
    note: 'мн. ч. discrepancies',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'untouched',
    word: 'untouched',
    translation: 'нетронутый',
    example: 'engine/ untouched.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'pre-existing',
    word: 'pre-existing',
    translation: 'уже существовавший, прежний',
    example: '184 passed (181 pre-existing + 3 new).',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'wire-in',
    word: 'wire in',
    translation: 'подключить, встроить',
    example: 'getHeadTree is wired in.',
    note: 'дословно «провести провод»',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 2038,
  },
  {
    id: 'toggle',
    word: 'toggle',
    translation: 'переключатель',
    example: 'Sorting is always on rather than a toggle.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'rather-than',
    word: 'rather than',
    translation: 'а не; вместо того чтобы',
    example: 'Sorting is always on rather than a toggle.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 292,
  },
  {
    id: 'criterion',
    word: 'criterion',
    translation: 'критерий',
    example: 'The task only asked for one sort criterion.',
    note: 'мн. ч. criteria',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'deploy',
    word: 'deploy',
    translation: 'выкладывать, развёртывать (на сервер)',
    example: 'Nothing was deployed.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'commit',
    word: 'commit',
    translation: 'коммит; фиксировать изменения',
    example: 'Changes to be committed:',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: 1322,
  },
  {
    id: 'working-tree',
    word: 'working tree',
    translation: 'рабочее дерево (файлы на диске)',
    example: 'nothing to commit, working tree clean',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'clean',
    word: 'clean',
    translation: 'чистый',
    example: 'nothing to commit, working tree clean',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: 842,
  },
  {
    id: 'untracked',
    word: 'untracked',
    translation: 'неотслеживаемый',
    example: 'Untracked files:',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'stage',
    word: 'stage',
    translation: 'добавить в индекс, подготовить к коммиту',
    example: 'Changes not staged for commit:',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: 551,
  },
  {
    id: 'branch',
    word: 'branch',
    translation: 'ветка',
    example: 'On branch master',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: 1407,
  },
  {
    id: 'repository',
    word: 'repository',
    translation: 'репозиторий, хранилище',
    example: 'Initialized empty Git repository',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'initialize',
    word: 'initialize',
    translation: 'инициализировать, создать с нуля',
    example: 'Initialized empty Git repository',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'empty',
    word: 'empty',
    translation: 'пустой',
    example: 'Initialized empty Git repository',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: 1592,
  },
  {
    id: 'existing',
    word: 'existing',
    translation: 'существующий',
    example: 'Reinitialized existing Git repository',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: 593,
  },
  {
    id: 'permission',
    word: 'permission',
    translation: 'разрешение, право доступа',
    example: 'Permission denied (publickey).',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 2414,
  },
  {
    id: 'deny',
    word: 'deny',
    translation: 'отказывать, запрещать',
    example: 'Permission denied (publickey).',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 1429,
  },
  {
    id: 'fatal',
    word: 'fatal',
    translation: 'фатальный — ошибка, после которой команда прекращает работу',
    example: 'fatal: cannot open file for reading',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: null,
  },
  {
    id: 'warning',
    word: 'warning',
    translation: 'предупреждение',
    example: 'cp: warning: behavior of -n is non-portable',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 1132,
  },
  {
    id: 'behavior',
    word: 'behavior',
    translation: 'поведение',
    example: 'cp: warning: behavior of -n is non-portable',
    note: 'британское написание — behaviour',
    kind: 'it',
    source: 'терминал',
    ngslRank: 706,
  },
  {
    id: 'non-portable',
    word: 'non-portable',
    translation: 'непереносимый — работает не везде одинаково',
    example: 'cp: warning: behavior of -n is non-portable',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: null,
  },
  {
    id: 'instead',
    word: 'instead',
    translation: 'вместо (этого)',
    example: 'Use --update=none instead.',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 553,
  },
  {
    id: 'directory',
    word: 'directory',
    translation: 'каталог, папка',
    example: 'No such file or directory',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: null,
  },
  {
    id: 'such',
    word: 'such',
    translation: 'такой',
    example: 'No such file or directory',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 100,
  },
  {
    id: 'access',
    word: 'access',
    translation: 'доступ; получить доступ',
    example: 'ls: cannot access \'/home/user/upload\'',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 802,
  },
  {
    id: 'build',
    word: 'build',
    translation: 'сборка; собирать',
    example: 'Build and lint clean.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 221,
  },
  {
    id: 'succeed',
    word: 'succeed',
    translation: 'успешно выполниться, добиться успеха',
    example: 'The build succeeds.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 1586,
  },
  {
    id: 'pass',
    word: 'pass',
    translation: 'проходить (о тесте)',
    example: '184 passed.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 416,
  },
  {
    id: 'transform',
    word: 'transform',
    translation: 'преобразовывать',
    example: '63 modules transformed.',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 2174,
  },
  {
    id: 'environment',
    word: 'environment',
    translation: 'окружение, среда',
    example: 'Building client environment for production...',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 712,
  },
  {
    id: 'production',
    word: 'production',
    translation: 'продакшен — рабочая, «боевая» среда',
    example: 'Building client environment for production...',
    note: '',
    kind: 'it',
    source: 'терминал',
    ngslRank: 713,
  },
  {
    id: 'apply',
    word: 'apply',
    translation: 'применять',
    example: '9 updates can be applied immediately.',
    note: '',
    kind: 'it',
    source: 'сервер',
    ngslRank: 611,
  },
  {
    id: 'immediately',
    word: 'immediately',
    translation: 'немедленно, сразу',
    example: '9 updates can be applied immediately.',
    note: '',
    kind: 'it',
    source: 'сервер',
    ngslRank: 988,
  },
  {
    id: 'update',
    word: 'update',
    translation: 'обновление; обновлять',
    example: '9 updates can be applied immediately.',
    note: '',
    kind: 'it',
    source: 'сервер',
    ngslRank: 1933,
  },
  {
    id: 'security',
    word: 'security',
    translation: 'безопасность',
    example: '2 additional security updates can be applied.',
    note: '',
    kind: 'it',
    source: 'сервер',
    ngslRank: 541,
  },
  {
    id: 'additional',
    word: 'additional',
    translation: 'дополнительный',
    example: '2 additional security updates can be applied.',
    note: '',
    kind: 'it',
    source: 'сервер',
    ngslRank: 1081,
  },
  {
    id: 'enable',
    word: 'enable',
    translation: 'включать',
    example: 'ESM Apps is not enabled.',
    note: 'обратное — disable',
    kind: 'it',
    source: 'сервер',
    ngslRank: 1352,
  },
  {
    id: 'maintenance',
    word: 'maintenance',
    translation: 'обслуживание, поддержка',
    example: 'Expanded Security Maintenance for Applications',
    note: '',
    kind: 'it',
    source: 'сервер',
    ngslRank: 2548,
  },
  {
    id: 'mode',
    word: 'mode',
    translation: 'режим',
    example: 'auto mode on',
    note: '',
    kind: 'it',
    source: 'Claude Code',
    ngslRank: 2204,
  },
  {
    id: 'cycle',
    word: 'cycle',
    translation: 'перебирать по кругу; цикл',
    example: 'shift+tab to cycle',
    note: '',
    kind: 'it',
    source: 'Claude Code',
    ngslRank: 1394,
  },
  {
    id: 'report',
    word: 'report',
    translation: 'отчёт; сообщать',
    example: 'Already reported this above.',
    note: '',
    kind: 'it',
    source: 'Claude Code',
    ngslRank: 166,
  },
  {
    id: 'above',
    word: 'above',
    translation: 'выше',
    example: 'Already reported this above.',
    note: 'обратное — below',
    kind: 'it',
    source: 'Claude Code',
    ngslRank: 440,
  },
  {
    id: 'complete',
    word: 'complete',
    translation: 'завершённый; завершать',
    example: 'The task is complete.',
    note: '',
    kind: 'it',
    source: 'Claude Code',
    ngslRank: 581,
  },
  {
    id: 'source',
    word: 'source',
    translation: 'источник; исходный код',
    example: 'The external source file was not touched.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 623,
  },
  {
    id: 'external',
    word: 'external',
    translation: 'внешний',
    example: 'The external source file was not touched.',
    note: '',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 2125,
  },
  {
    id: 'dependency',
    word: 'dependency',
    translation: 'зависимость (подключаемая библиотека)',
    example: 'Do not add new dependencies.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: null,
  },
  {
    id: 'refactor',
    word: 'refactor',
    translation: 'рефакторинг — переделать код, не меняя поведения',
    example: 'refactor: take HEAD tree from engine',
    note: '',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'feature',
    word: 'feature',
    translation: 'функция, возможность',
    example: 'A new feature of the site.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 635,
  },
  {
    id: 'issue',
    word: 'issue',
    translation: 'проблема; задача в трекере',
    example: 'I opened an issue on GitHub.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 218,
  },
  {
    id: 'review',
    word: 'review',
    translation: 'проверка, ревью; проверять',
    example: 'The code is ready for review.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 730,
  },
  {
    id: 'finding',
    word: 'finding',
    translation: 'находка, выявленная проблема',
    example: 'The reviewer listed the findings by severity.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 81,
  },
  {
    id: 'severity',
    word: 'severity',
    translation: 'серьёзность, критичность',
    example: 'The reviewer listed the findings by severity.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: null,
  },
  {
    id: 'scope',
    word: 'scope',
    translation: 'область, рамки',
    example: 'This feature is out of scope for now.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 2559,
  },
  {
    id: 'expected',
    word: 'expected',
    translation: 'ожидаемый',
    example: 'Expected: 249 books. Actual: 248.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 314,
  },
  {
    id: 'actual',
    word: 'actual',
    translation: 'фактический, настоящий',
    example: 'Expected: 249 books. Actual: 248.',
    note: 'ложный друг: НЕ «актуальный»',
    kind: 'it',
    source: '',
    ngslRank: 1335,
  },
  {
    id: 'current',
    word: 'current',
    translation: 'текущий, актуальный',
    example: 'What is the current version?',
    note: '«актуальный» — это current',
    kind: 'it',
    source: '',
    ngslRank: 590,
  },
  {
    id: 'deprecated',
    word: 'deprecated',
    translation: 'устаревший, не рекомендуемый к использованию',
    example: 'This option is deprecated.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: null,
  },
  {
    id: 'resolve',
    word: 'resolve',
    translation: 'разрешать, устранять (проблему)',
    example: 'Resolve the merge conflict first.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 1777,
  },
  {
    id: 'conflict',
    word: 'conflict',
    translation: 'конфликт',
    example: 'Resolve the merge conflict first.',
    note: '',
    kind: 'it',
    source: '',
    ngslRank: 1184,
  },
  {
    id: 'provide',
    word: 'provide',
    translation: 'предоставлять, обеспечивать',
    example: 'The engine provides a function for that.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 205,
  },
  {
    id: 'require',
    word: 'require',
    translation: 'требовать',
    example: 'This step requires a password.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 402,
  },
  {
    id: 'include',
    word: 'include',
    translation: 'включать (в состав)',
    example: 'The report includes the test results.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 163,
  },
  {
    id: 'allow',
    word: 'allow',
    translation: 'позволять, разрешать',
    example: 'The rule allows only one change.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 324,
  },
  {
    id: 'remain',
    word: 'remain',
    translation: 'оставаться',
    example: 'Two tasks remain.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 374,
  },
  {
    id: 'consider',
    word: 'consider',
    translation: 'рассматривать; считать',
    example: 'Consider a smaller step.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 295,
  },
  {
    id: 'appear',
    word: 'appear',
    translation: 'появляться; казаться',
    example: 'A new file appears in the list.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 405,
  },
  {
    id: 'suggest',
    word: 'suggest',
    translation: 'предлагать, советовать',
    example: 'I suggest a different approach.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 329,
  },
  {
    id: 'contain',
    word: 'contain',
    translation: 'содержать',
    example: 'The folder contains three files.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 663,
  },
  {
    id: 'likely',
    word: 'likely',
    translation: 'вероятно; вероятный',
    example: 'This is likely a typo.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 535,
  },
  {
    id: 'certain',
    word: 'certain',
    translation: 'определённый; уверенный',
    example: 'I am certain it works.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 451,
  },
  {
    id: 'several',
    word: 'several',
    translation: 'несколько',
    example: 'Several tests failed.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 348,
  },
  {
    id: 'various',
    word: 'various',
    translation: 'различные, разные',
    example: 'The book covers various topics.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 682,
  },
  {
    id: 'whether',
    word: 'whether',
    translation: 'ли',
    example: 'Check whether the file exists.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 273,
  },
  {
    id: 'although',
    word: 'although',
    translation: 'хотя',
    example: 'Although it works, the code is slow.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 278,
  },
  {
    id: 'however',
    word: 'however',
    translation: 'однако',
    example: 'It works. However, it is slow.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 203,
  },
  {
    id: 'therefore',
    word: 'therefore',
    translation: 'поэтому, следовательно',
    example: 'The test failed; therefore, we stopped.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 525,
  },
  {
    id: 'either',
    word: 'either',
    translation: 'любой из двух; either … or — либо … либо',
    example: 'Use either Chrome or Firefox.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 371,
  },
  {
    id: 'enough',
    word: 'enough',
    translation: 'достаточно',
    example: 'One test is not enough.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 267,
  },
  {
    id: 'within',
    word: 'within',
    translation: 'в пределах, внутри',
    example: 'Finish the task within a day.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 285,
  },
  {
    id: 'without',
    word: 'without',
    translation: 'без',
    example: 'Commit without the extra file.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 212,
  },
  {
    id: 'against',
    word: 'against',
    translation: 'против; по сравнению с',
    example: 'Check the result against the documentation.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 224,
  },
  {
    id: 'since',
    word: 'since',
    translation: 'с (какого-то момента); так как',
    example: 'The site has been online since Friday.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 191,
  },
  {
    id: 'until',
    word: 'until',
    translation: 'до, пока не',
    example: 'Wait until the build finishes.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 255,
  },
  {
    id: 'despite',
    word: 'despite',
    translation: 'несмотря на',
    example: 'Despite the warning, it worked.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 771,
  },
  {
    id: 'following',
    word: 'following',
    translation: 'следующий, нижеследующий',
    example: 'Run the following command.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 188,
  },
  {
    id: 'previous',
    word: 'previous',
    translation: 'предыдущий',
    example: 'Go back to the previous step.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 922,
  },
  {
    id: 'particular',
    word: 'particular',
    translation: 'конкретный, определённый',
    example: 'Look at this particular line.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 467,
  },
  {
    id: 'specific',
    word: 'specific',
    translation: 'конкретный, определённый',
    example: 'Give me a specific example.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 791,
  },
  {
    id: 'common',
    word: 'common',
    translation: 'распространённый; общий',
    example: 'This is a common mistake.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 567,
  },
  {
    id: 'similar',
    word: 'similar',
    translation: 'похожий',
    example: 'The two files are similar.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 594,
  },
  {
    id: 'ensure',
    word: 'ensure',
    translation: 'обеспечивать, гарантировать',
    example: 'Tests ensure the rules hold.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1153,
  },
  {
    id: 'achieve',
    word: 'achieve',
    translation: 'достигать',
    example: 'We achieved the goal.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 746,
  },
  {
    id: 'reduce',
    word: 'reduce',
    translation: 'уменьшать, сокращать',
    example: 'This change reduces the file size.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 584,
  },
  {
    id: 'increase',
    word: 'increase',
    translation: 'увеличивать(ся)',
    example: 'The number of tests increased.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 230,
  },
  {
    id: 'improve',
    word: 'improve',
    translation: 'улучшать',
    example: 'The new version improves search.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 508,
  },
  {
    id: 'handle',
    word: 'handle',
    translation: 'обрабатывать; справляться',
    example: 'The engine handles errors.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1041,
  },
  {
    id: 'maintain',
    word: 'maintain',
    translation: 'поддерживать, сопровождать',
    example: 'Who maintains this project?',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 943,
  },
  {
    id: 'support',
    word: 'support',
    translation: 'поддерживать; поддержка',
    example: 'The browser supports this feature.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 272,
  },
  {
    id: 'prevent',
    word: 'prevent',
    translation: 'предотвращать',
    example: 'The test prevents old bugs from returning.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1026,
  },
  {
    id: 'affect',
    word: 'affect',
    translation: 'влиять на',
    example: 'The change does not affect section 1.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 639,
  },
  {
    id: 'involve',
    word: 'involve',
    translation: 'включать в себя, затрагивать',
    example: 'The task involves two files.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 379,
  },
  {
    id: 'determine',
    word: 'determine',
    translation: 'определять',
    example: 'The engine determines what HEAD points to.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 708,
  },
  {
    id: 'indicate',
    word: 'indicate',
    translation: 'указывать, показывать',
    example: 'The red line indicates an error.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 819,
  },
  {
    id: 'obtain',
    word: 'obtain',
    translation: 'получать, добывать',
    example: 'Obtain the key from the server.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: null,
  },
  {
    id: 'perform',
    word: 'perform',
    translation: 'выполнять',
    example: 'The agent performs the task.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 935,
  },
  {
    id: 'receive',
    word: 'receive',
    translation: 'получать',
    example: 'I received the report.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 396,
  },
  {
    id: 'replace',
    word: 'replace',
    translation: 'заменять',
    example: 'Replace the old line with the new one.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 994,
  },
  {
    id: 'avoid',
    word: 'avoid',
    translation: 'избегать',
    example: 'Avoid pasting several lines at once.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 851,
  },
  {
    id: 'attempt',
    word: 'attempt',
    translation: 'попытка; пытаться',
    example: 'The first attempt failed.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 686,
  },
  {
    id: 'describe',
    word: 'describe',
    translation: 'описывать',
    example: 'Describe the problem in one line.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 457,
  },
  {
    id: 'explain',
    word: 'explain',
    translation: 'объяснять',
    example: 'Explain why this step is needed.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 489,
  },
  {
    id: 'identify',
    word: 'identify',
    translation: 'выявлять, определять',
    example: 'The reviewer identified two problems.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 805,
  },
  {
    id: 'measure',
    word: 'measure',
    translation: 'измерять; мера',
    example: 'Measure how long the task takes.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 532,
  },
  {
    id: 'notice',
    word: 'notice',
    translation: 'замечать',
    example: 'I noticed a white scrollbar.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 664,
  },
  {
    id: 'prepare',
    word: 'prepare',
    translation: 'готовить(ся)',
    example: 'Prepare the data first.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 604,
  },
  {
    id: 'refer-to',
    word: 'refer to',
    translation: 'ссылаться на; относиться к',
    example: 'This note refers to section 2.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 866,
  },
  {
    id: 'rely-on',
    word: 'rely on',
    translation: 'полагаться на',
    example: 'Do not rely on the report alone.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1584,
  },
  {
    id: 'respond',
    word: 'respond',
    translation: 'отвечать, реагировать',
    example: 'The server does not respond.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1116,
  },
  {
    id: 'select',
    word: 'select',
    translation: 'выбирать',
    example: 'Select two categories.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1173,
  },
  {
    id: 'share',
    word: 'share',
    translation: 'делиться; доля',
    example: 'Share the link with the team.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 353,
  },
  {
    id: 'solve',
    word: 'solve',
    translation: 'решать (задачу, проблему)',
    example: 'This change solves the problem.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1221,
  },
  {
    id: 'store',
    word: 'store',
    translation: 'хранить; магазин',
    example: 'The browser stores the progress.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 617,
  },
  {
    id: 'cause',
    word: 'cause',
    translation: 'причина; вызывать',
    example: 'What caused the error?',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 319,
  },
  {
    id: 'purpose',
    word: 'purpose',
    translation: 'цель, назначение',
    example: 'What is the purpose of this file?',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 735,
  },
  {
    id: 'result',
    word: 'result',
    translation: 'результат',
    example: 'Send me the result.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 233,
  },
  {
    id: 'value',
    word: 'value',
    translation: 'значение; ценность',
    example: 'The value is empty.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 342,
  },
  {
    id: 'amount',
    word: 'amount',
    translation: 'количество (неисчисляемого)',
    example: 'A small amount of data.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 507,
  },
  {
    id: 'approach',
    word: 'approach',
    translation: 'подход',
    example: 'I suggest a different approach.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 495,
  },
  {
    id: 'option',
    word: 'option',
    translation: 'вариант, опция',
    example: 'There are two options.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 860,
  },
  {
    id: 'detail',
    word: 'detail',
    translation: 'подробность, деталь',
    example: 'Add more details.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 472,
  },
  {
    id: 'level',
    word: 'level',
    translation: 'уровень',
    example: 'The top level of the folder.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 262,
  },
  {
    id: 'process',
    word: 'process',
    translation: 'процесс; обрабатывать',
    example: 'The process takes five minutes.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 286,
  },
  {
    id: 'content',
    word: 'content',
    translation: 'содержимое',
    example: 'The content of the file is the same.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 1025,
  },
  {
    id: 'though',
    word: 'though',
    translation: 'хотя; впрочем',
    example: 'It works, though it is slow.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 227,
  },
  {
    id: 'quite',
    word: 'quite',
    translation: 'вполне, довольно',
    example: 'The task is quite small.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 277,
  },
  {
    id: 'already',
    word: 'already',
    translation: 'уже',
    example: 'The file already exists.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 302,
  },
  {
    id: 'yet',
    word: 'yet',
    translation: 'ещё (в отрицании); уже (в вопросе)',
    example: 'No commits yet.',
    note: '',
    kind: 'general',
    source: 'git',
    ngslRank: 311,
  },
  {
    id: 'still',
    word: 'still',
    translation: 'всё ещё',
    example: 'The server is still running.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 119,
  },
  {
    id: 'rather',
    word: 'rather',
    translation: 'скорее, довольно',
    example: 'The change is rather small.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 292,
  },
  {
    id: 'almost',
    word: 'almost',
    translation: 'почти',
    example: 'The build is almost done.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 307,
  },
  {
    id: 'actually',
    word: 'actually',
    translation: 'на самом деле, фактически',
    example: 'It actually works.',
    note: 'ложный друг: НЕ «актуально»',
    kind: 'general',
    source: '',
    ngslRank: 291,
  },

  // ============================================================
  // Пополнение: 50 IT-слов из реального контекста репозитория
  // (docs/git-trainer/reviews/*.md, docs/git-trainer/target.md, docs/git-trainer/spec.md,
  // docs/agent-practices.md) и 50 общих слов по рангу NGSL.
  // ============================================================

  {
    id: 'merge',
    word: 'merge',
    translation: 'слияние; сливать (ветки)',
    example: 'Merge branch \'feature\' into develop',
    note: 'docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'fast-forward',
    word: 'fast-forward',
    translation: 'перемотка — слияние без создания нового коммита',
    example: 'Fast-forward',
    note: 'полная форма вывода — Updating <hash>..<hash>, затем Fast-forward; docs/git-trainer/reviews/review-03.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'pathspec',
    word: 'pathspec',
    translation: 'путь или шаблон пути, переданный команде git',
    example: 'error: pathspec \'...\' did not match any file(s) known to git',
    note: 'docs/git-trainer/target.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'worktree',
    word: 'worktree',
    translation: 'рабочее дерево, связанное с текущей веткой',
    example: 'error: cannot delete branch \'master\' used by worktree at \'/site\'',
    note: 'docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'overwrite',
    word: 'overwrite',
    translation: 'перезаписывать',
    example: 'error: Your local changes to the following files would be overwritten by merge:',
    note: 'docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'switch',
    word: 'switch',
    translation: 'переключаться (на другую ветку)',
    example: 'Please commit your changes or stash them before you switch branches.',
    note: 'docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1463,
  },
  {
    id: 'stash',
    word: 'stash',
    translation: 'спрятать незакоммиченные изменения',
    example: 'No local changes to save',
    note: 'команда git stash; здесь — отказ, когда прятать нечего; docs/git-trainer/spec.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'revert',
    word: 'revert',
    translation: 'отменить коммит новым обратным коммитом',
    example: 'git revert HEAD',
    note: 'не удаляет историю, в отличие от reset; docs/git-trainer/spec.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'specify',
    word: 'specify',
    translation: 'указывать, задавать',
    example: 'Nothing specified, nothing added.',
    note: 'docs/git-trainer/reviews/review-02.md',
    kind: 'it',
    source: 'git',
    ngslRank: 2326,
  },
  {
    id: 'add',
    word: 'add',
    translation: 'добавлять',
    example: 'Nothing specified, nothing added.',
    note: 'docs/git-trainer/reviews/review-02.md',
    kind: 'it',
    source: 'git',
    ngslRank: 414,
  },
  {
    id: 'disable',
    word: 'disable',
    translation: 'отключать',
    example: 'Bash is disabled for this session, in subagents as well as here.',
    note: 'противоположность — enable; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: null,
  },
  {
    id: 'session',
    word: 'session',
    translation: 'сессия, сеанс работы',
    example: 'Bash is disabled for this session, in subagents as well as here.',
    note: 'docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'отчёт агента',
    ngslRank: 1558,
  },
  {
    id: 'delete',
    word: 'delete',
    translation: 'удалять',
    example: 'Deleted branch feature (was fcc6183).',
    note: 'docs/git-trainer/reviews/review-10.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'abort',
    word: 'abort',
    translation: 'прерывать выполнение',
    example: 'Aborting commit due to empty commit message.',
    note: 'docs/git-trainer/reviews/review-03.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'remote',
    word: 'remote',
    translation: 'удалённый (сервер, репозиторий)',
    example: 'fatal: No remote for the current branch.',
    note: 'docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 2497,
  },
  {
    id: 'unknown',
    word: 'unknown',
    translation: 'неизвестный',
    example: 'unknown option `b\'',
    note: 'docs/git-trainer/reviews/review-05.md',
    kind: 'it',
    source: 'git',
    ngslRank: 2043,
  },
  {
    id: 'strategy',
    word: 'strategy',
    translation: 'стратегия',
    example: 'Merge made by the \'ort\' strategy.',
    note: 'docs/git-trainer/reviews/review-04.md',
    kind: 'it',
    source: 'git',
    ngslRank: 839,
  },
  {
    id: 'unrelated',
    word: 'unrelated',
    translation: 'несвязанный, посторонний',
    example:
      'To avoid recording unrelated changes in the merge commit, git pull and git merge will also abort if there are any changes registered in the index relative to the HEAD commit.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'register',
    word: 'register',
    translation: 'регистрировать, учитывать',
    example:
      'To avoid recording unrelated changes in the merge commit, git pull and git merge will also abort if there are any changes registered in the index relative to the HEAD commit.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1500,
  },
  {
    id: 'relative',
    word: 'relative',
    translation: 'относительный',
    example:
      'To avoid recording unrelated changes in the merge commit, git pull and git merge will also abort if there are any changes registered in the index relative to the HEAD commit.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1088,
  },
  {
    id: 'narrow',
    word: 'narrow',
    translation: 'узкий',
    example:
      'Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match HEAD.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1585,
  },
  {
    id: 'exception',
    word: 'exception',
    translation: 'исключение',
    example:
      'Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match HEAD.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1908,
  },
  {
    id: 'depend',
    word: 'depend',
    translation: 'зависеть',
    example:
      'Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match HEAD.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 731,
  },
  {
    id: 'generally',
    word: 'generally',
    translation: 'как правило, в целом',
    example:
      'Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match HEAD.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 848,
  },
  {
    id: 'index',
    word: 'index',
    translation: 'индекс — область подготовленных изменений в git',
    example:
      'Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match HEAD.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1709,
  },
  {
    id: 'move',
    word: 'move',
    translation: 'перемещать',
    example: 'Please move or remove them before you switch branches.',
    note: 'docs/git-trainer/reviews/review-03.md',
    kind: 'it',
    source: 'git',
    ngslRank: 200,
  },
  {
    id: 'remove',
    word: 'remove',
    translation: 'удалять, убирать',
    example: 'Please move or remove them before you switch branches.',
    note: 'в git есть отдельная команда git rm — «убрать файл», это другое слово, чем delete (ветка); docs/git-trainer/reviews/review-03.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1053,
  },
  {
    id: 'checkout',
    word: 'checkout',
    translation: 'переключение на ветку/коммит с обновлением рабочего дерева',
    example: 'error: Your local changes to the following files would be overwritten by checkout:',
    note: 'docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'save',
    word: 'save',
    translation: 'сохранять',
    example: 'No local changes to save',
    note: 'docs/git-trainer/spec.md',
    kind: 'it',
    source: 'git',
    ngslRank: 566,
  },
  {
    id: 'graph',
    word: 'graph',
    translation: 'граф (истории коммитов)',
    example: 'git log --graph',
    note: 'docs/git-trainer/reviews/review-10.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'valid',
    word: 'valid',
    translation: 'действительный, допустимый',
    example: 'fatal: \'a*b\' is not a valid branch name',
    note: 'docs/git-trainer/reviews/review-06.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'object',
    word: 'object',
    translation: 'объект',
    example: 'not a valid object name',
    note: 'здесь — git-объект (коммит, дерево, blob); docs/git-trainer/spec.md',
    kind: 'it',
    source: 'git',
    ngslRank: 942,
  },
  {
    id: 'rule',
    word: 'rule',
    translation: 'правило',
    example:
      'Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match HEAD.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 415,
  },
  {
    id: 'use',
    word: 'use',
    translation: 'использование; использовать',
    example:
      'Special narrow exceptions to this rule may exist depending on which merge strategy is in use, but generally, the index must match HEAD.',
    note: 'цитата из документации git-merge; docs/git-trainer/reviews/review-01.md',
    kind: 'it',
    source: 'git',
    ngslRank: 68,
  },
  {
    id: 'lock',
    word: 'lock',
    translation: 'блокировать; захватывать (ссылку)',
    example:
      'fatal: cannot lock ref \'refs/heads/feature\': \'refs/heads/feature/a\' exists; cannot create \'refs/heads/feature\'',
    note: 'docs/git-trainer/reviews/review-07.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1604,
  },
  {
    id: 'sense',
    word: 'sense',
    translation: 'смысл',
    example: 'fatal: paths \'-m ...\' with -a does not make sense',
    note: 'make sense — «иметь смысл»; docs/git-trainer/reviews/review-06.md',
    kind: 'it',
    source: 'git',
    ngslRank: 412,
  },
  {
    id: 'sure',
    word: 'sure',
    translation: 'уверенный',
    example: 'hint: If you are sure you want to delete it, run \'git branch -D a\'',
    note: 'docs/git-trainer/reviews/review-09.md',
    kind: 'it',
    source: 'git',
    ngslRank: 279,
  },
  {
    id: 'run',
    word: 'run',
    translation: 'запускать (команду)',
    example: 'hint: If you are sure you want to delete it, run \'git branch -D a\'',
    note: 'docs/git-trainer/reviews/review-09.md',
    kind: 'it',
    source: 'git',
    ngslRank: 192,
  },
  {
    id: 'usage',
    word: 'usage',
    translation: 'использование; краткая справка по команде',
    example: 'usage: git branch [<options>] [-r | -a] [--merged] [--no-merged] ...',
    note: 'docs/git-trainer/reviews/review-07.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'ambiguous',
    word: 'ambiguous',
    translation: 'неоднозначный',
    example: 'error: ambiguous option: verif=x (could be --verify-signatures or --no-no-verify)',
    note: 'docs/git-trainer/reviews/review-07.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'together',
    word: 'together',
    translation: 'вместе',
    example: 'fatal: options \'-i/--include\' and \'-a/--all\' cannot be used together',
    note: 'docs/git-trainer/reviews/review-07.md',
    kind: 'it',
    source: 'git',
    ngslRank: 294,
  },
  {
    id: 'editor',
    word: 'editor',
    translation: 'редактор (текстовый)',
    example: 'error: there was a problem with the editor \'false\'',
    note: 'docs/git-trainer/reviews/review-07.md',
    kind: 'it',
    source: 'git',
    ngslRank: 1423,
  },
  {
    id: 'problem',
    word: 'problem',
    translation: 'проблема',
    example: 'error: there was a problem with the editor \'false\'',
    note: 'docs/git-trainer/reviews/review-07.md',
    kind: 'it',
    source: 'git',
    ngslRank: 120,
  },
  {
    id: 'create',
    word: 'create',
    translation: 'создавать',
    example:
      'fatal: cannot lock ref \'refs/heads/feature\': \'refs/heads/feature/a\' exists; cannot create \'refs/heads/feature\'',
    note: 'docs/git-trainer/reviews/review-07.md',
    kind: 'it',
    source: 'git',
    ngslRank: 386,
  },
  {
    id: 'note',
    word: 'note',
    translation: 'заметка, примечание; отмечать',
    example: 'Note: switching to \'master~0\'. … HEAD is now at …',
    note: 'docs/git-trainer/reviews/review-06.md',
    kind: 'it',
    source: 'git',
    ngslRank: 384,
  },
  {
    id: 'direct',
    word: 'direct',
    translation: 'прямой',
    example: 'error: option `--track\' expects "direct" or "inherit"',
    note: 'docs/git-trainer/reviews/review-06.md',
    kind: 'it',
    source: 'git',
    ngslRank: 724,
  },
  {
    id: 'inherit',
    word: 'inherit',
    translation: 'наследовать',
    example: 'error: option `--track\' expects "direct" or "inherit"',
    note: 'docs/git-trainer/reviews/review-06.md',
    kind: 'it',
    source: 'git',
    ngslRank: null,
  },
  {
    id: 'take',
    word: 'take',
    translation: 'принимать (значение); брать',
    example: 'error: option `delete\' takes no value',
    note: 'docs/git-trainer/reviews/review-06.md',
    kind: 'it',
    source: 'git',
    ngslRank: 59,
  },
  {
    id: 'hint',
    word: 'hint',
    translation: 'подсказка',
    example: 'hint: Disable this message with "git config set advice.forceDeleteBranch false"',
    note: 'docs/git-trainer/reviews/review-10.md',
    kind: 'it',
    source: 'git',
    ngslRank: 2689,
  },
  {
    id: 'local',
    word: 'local',
    translation: 'локальный',
    example: 'No local changes to save',
    note: 'docs/git-trainer/spec.md',
    kind: 'it',
    source: 'git',
    ngslRank: 300,
  },

  // ============================================================
  // Пополнение: 50 общих слов по рангу NGSL (NGSL_1.2_stats.csv),
  // ранги 30–103. Пропущены служебные слова (артикли, местоимения,
  // предлоги, союзы, вспомогательные и модальные глаголы, числительные)
  // и слова, уже входящие в этот список.
  // ============================================================

  {
    id: 'say',
    word: 'say',
    translation: 'говорить, сказать',
    example: 'Say the command out loud before typing it.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 30,
  },
  {
    id: 'go',
    word: 'go',
    translation: 'идти, переходить',
    example: 'The build will go faster tomorrow.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 31,
  },
  {
    id: 'all',
    word: 'all',
    translation: 'весь, все',
    example: 'All tests passed.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 33,
  },
  {
    id: 'there',
    word: 'there',
    translation: 'там; there is/are — имеется',
    example: 'There is a bug in this function.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 40,
  },
  {
    id: 'know',
    word: 'know',
    translation: 'знать',
    example: 'I know the answer.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 41,
  },
  {
    id: 'more',
    word: 'more',
    translation: 'больше',
    example: 'We need more tests.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 42,
  },
  {
    id: 'get',
    word: 'get',
    translation: 'получать; становиться',
    example: 'Get the latest version from the server.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 43,
  },
  {
    id: 'like',
    word: 'like',
    translation: 'нравиться; подобно',
    example: 'I like this approach.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 45,
  },
  {
    id: 'think',
    word: 'think',
    translation: 'думать',
    example: 'I think the fix is correct.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 47,
  },
  {
    id: 'make',
    word: 'make',
    translation: 'делать, изготавливать',
    example: 'Make the change and save the file.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 48,
  },
  {
    id: 'time',
    word: 'time',
    translation: 'время',
    example: 'This is the first time I saw this error.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 49,
  },
  {
    id: 'see',
    word: 'see',
    translation: 'видеть',
    example: 'You can see the result on the screen.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 50,
  },
  {
    id: 'some',
    word: 'some',
    translation: 'несколько, некоторый',
    example: 'Some tests are still failing.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 53,
  },
  {
    id: 'other',
    word: 'other',
    translation: 'другой',
    example: 'Check the other file too.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 54,
  },
  {
    id: 'out',
    word: 'out',
    translation: 'наружу; вне',
    example: 'Take the old code out.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 55,
  },
  {
    id: 'good',
    word: 'good',
    translation: 'хороший',
    example: 'This is a good solution.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 56,
  },
  {
    id: 'people',
    word: 'people',
    translation: 'люди',
    example: 'Many people use this tool.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 57,
  },
  {
    id: 'year',
    word: 'year',
    translation: 'год',
    example: 'The project started last year.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 58,
  },
  {
    id: 'well',
    word: 'well',
    translation: 'хорошо; ну (вводное слово)',
    example: 'The site works well now.',
    note: 'в начале фразы — вводное «ну»',
    kind: 'general',
    source: '',
    ngslRank: 61,
  },
  {
    id: 'very',
    word: 'very',
    translation: 'очень',
    example: 'The task was very simple.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 63,
  },
  {
    id: 'just',
    word: 'just',
    translation: 'только что; просто',
    example: 'It is just a small typo.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 64,
  },
  {
    id: 'come',
    word: 'come',
    translation: 'приходить',
    example: 'New updates come every week.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 65,
  },
  {
    id: 'work',
    word: 'work',
    translation: 'работать; работа',
    example: 'Does the script still work?',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 67,
  },
  {
    id: 'now',
    word: 'now',
    translation: 'сейчас',
    example: 'The build is ready now.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 70,
  },
  {
    id: 'then',
    word: 'then',
    translation: 'тогда, затем',
    example: 'First run the tests, then deploy.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 71,
  },
  {
    id: 'also',
    word: 'also',
    translation: 'тоже, также',
    example: 'The report also lists warnings.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 72,
  },
  {
    id: 'only',
    word: 'only',
    translation: 'только',
    example: 'Only one file changed.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 74,
  },
  {
    id: 'look',
    word: 'look',
    translation: 'смотреть; выглядеть',
    example: 'Look at the last line of the log.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 75,
  },
  {
    id: 'want',
    word: 'want',
    translation: 'хотеть',
    example: 'I want a simpler solution.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 76,
  },
  {
    id: 'give',
    word: 'give',
    translation: 'давать',
    example: 'Give the file a clear name.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 77,
  },
  {
    id: 'new',
    word: 'new',
    translation: 'новый',
    example: 'We created a new branch.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 79,
  },
  {
    id: 'way',
    word: 'way',
    translation: 'способ, путь',
    example: 'There is a better way to do this.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 80,
  },
  {
    id: 'find',
    word: 'find',
    translation: 'находить',
    example: 'Find the line that caused the error.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 81,
  },
  {
    id: 'any',
    word: 'any',
    translation: 'любой; какой-нибудь',
    example: 'Is there any error in the log?',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 83,
  },
  {
    id: 'day',
    word: 'day',
    translation: 'день',
    example: 'The site went live the next day.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 85,
  },
  {
    id: 'where',
    word: 'where',
    translation: 'где, куда',
    example: 'Show me where the bug is.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 86,
  },
  {
    id: 'thing',
    word: 'thing',
    translation: 'вещь',
    example: 'One thing is still unclear.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 87,
  },
  {
    id: 'most',
    word: 'most',
    translation: 'большинство; наиболее',
    example: 'Most tests pass already.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 88,
  },
  {
    id: 'need',
    word: 'need',
    translation: 'нуждаться',
    example: 'You need a password to log in.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 90,
  },
  {
    id: 'much',
    word: 'much',
    translation: 'много (о неисчисляемом)',
    example: 'The file did not change much.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 91,
  },
  {
    id: 'right',
    word: 'right',
    translation: 'правильный; право',
    example: 'Type the command right this time.',
    note: 'также «право» (сущ.) и «правый»',
    kind: 'general',
    source: '',
    ngslRank: 92,
  },
  {
    id: 'how',
    word: 'how',
    translation: 'как',
    example: 'Show me how it works.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 93,
  },
  {
    id: 'back',
    word: 'back',
    translation: 'назад; спина',
    example: 'Go back to the previous step.',
    note: 'также «спина» (сущ.)',
    kind: 'general',
    source: '',
    ngslRank: 94,
  },
  {
    id: 'mean',
    word: 'mean',
    translation: 'означать; злой; средний',
    example: 'What does this error mean?',
    note: 'также «злой» (прил.) и «среднее значение»',
    kind: 'general',
    source: '',
    ngslRank: 95,
  },
  {
    id: 'even',
    word: 'even',
    translation: 'даже',
    example: 'The build passed even without the fix.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 96,
  },
  {
    id: 'here',
    word: 'here',
    translation: 'здесь',
    example: 'The problem starts here.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 98,
  },
  {
    id: 'many',
    word: 'many',
    translation: 'много (об исчисляемом)',
    example: 'There are many open questions.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 99,
  },
  {
    id: 'last',
    word: 'last',
    translation: 'последний; длиться',
    example: 'Check the last commit.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 101,
  },
  {
    id: 'child',
    word: 'child',
    translation: 'ребёнок',
    example: 'The folder has one child directory.',
    note: 'мн. ч. children',
    kind: 'general',
    source: '',
    ngslRank: 102,
  },
  {
    id: 'tell',
    word: 'tell',
    translation: 'рассказывать, говорить',
    example: 'The log can tell you what happened.',
    note: '',
    kind: 'general',
    source: '',
    ngslRank: 103,
  },
]

/** id всех слов в порядке списка выше — то, что принимают createSession/getStats движка. */
export const englishWordIds: string[] = englishWords.map((w) => w.id)

const wordsById = new Map(englishWords.map((w) => [w.id, w]))

/** Данные слова по id. Возвращает undefined, если id не из этого списка (не должно случаться). */
export function getWordById(id: string): EnglishWord | undefined {
  return wordsById.get(id)
}
