import sys, json
from playwright.sync_api import sync_playwright
res=[]
def check(name, cond, extra=""):
    res.append(bool(cond)); print(("  PASS " if cond else "  FAIL ") + name + (f"  [{extra}]" if extra else ""))
U12="file:///mnt/user-data/outputs/git-trenazher_15.html"; U13="file:///mnt/user-data/outputs/git-trenazher_15.html"
def fresh(br, url, **kw):
    ctx = br.new_context(viewport=kw.pop("viewport", {"width": 1280, "height": 900}), **kw)
    pg = ctx.new_page(); pg.route("**/fonts.g*/**", lambda r: r.abort())
    pg.errs = []; pg.on("pageerror", lambda e: pg.errs.append(str(e)))
    pg.goto(url, wait_until="domcontentloaded"); pg.wait_for_selector(".nav-item"); pg.locator(".nav-item").nth(6).click(); pg.wait_for_timeout(100); return pg
def ign(pg, t): pg.fill("#gitignore-input-ch7", t); pg.wait_for_timeout(40)
def rows(pg): return pg.evaluate("Object.fromEntries([...document.querySelectorAll('#gitignore-rows-ch7 .file-check-row')].map(r=>[r.querySelector('.fc-file > span').textContent, r.querySelector('.pill').classList.contains('pill-ignored')]))")
def msg(pg, t): pg.fill("#commitmsg-input-ch7", t); pg.wait_for_timeout(40); return pg.inner_text("#msg-report-ch7")
def flags(pg): return pg.eval_on_selector_all(".mission", "els => els.map(e => e.classList.contains('done'))")
def term(pg, t): 
    i = pg.locator("#term-in-alias-ch7"); i.fill(t); i.press("Enter"); pg.wait_for_timeout(60)
def last(pg): return pg.evaluate("(()=>{const h=STATE.chapters.ch7.aliasHist; return h[h.length-1]})()")
with sync_playwright() as p:
    br = p.chromium.launch(args=["--no-sandbox"]); errs=[]
    print("=== ДО (_12) ===")
    pg = fresh(br, U12)
    ign(pg, "node_modules\nbuild"); r = pg.eval_on_selector_all("#gitignore-rows-ch7 .file-check-row", "e=>e.map(x=>x.innerText.replace(/\\n/g,' '))"); print("  правила без слэша `node_modules`, `build`:", [x for x in r if 'node_modules' in x or 'build' in x])
    ign(pg, "*.log\n!debug.log"); r = pg.eval_on_selector_all("#gitignore-rows-ch7 .file-check-row", "e=>e.map(x=>x.innerText.replace(/\\n/g,' '))"); print("  `*.log` + `!debug.log`:", [x for x in r if 'debug' in x])
    for m in ["Fix #42", "fix bug", "Опечатка в README", "asdf asdf", "Добавить валидацию.\nбез пустой строки"]:
        pg.fill("#commitmsg-input-ch7", m); pg.wait_for_timeout(30); print("  сообщение", repr(m), "→", pg.inner_text("#msg-report-ch7").replace("\n"," | ")[:110])
    print("\n=== ПОСЛЕ (_13) ===")
    pg = fresh(br, U13); errs.append(pg.errs)
    check("0 миссии: 4 штуки, ни одна не выполнена", flags(pg)==[False]*4, str(flags(pg)))
    check("0 по умолчанию: .env и .env.example оба игнорируются", rows(pg)['.env'] and rows(pg)['.env.example'])
    # gitignore
    ign(pg, "node_modules"); r=rows(pg); check("1 `node_modules` без слэша: игнорирует и корневую, и вложенную папку", r['node_modules/react/index.js'] and r['packages/ui/node_modules/x.js'], str({k:v for k,v in r.items() if 'node' in k}))
    ign(pg, "build"); r=rows(pg); check("1 `build` без слэша: папки build/ на любом уровне; файл src/build.js (имя другое) — нет", r['build/bundle.js'] and r['docs/build/index.html'] and not r['src/build.js'] and not r['app.js'])
    ign(pg, "build/"); r=rows(pg); check("1 `build/`: только папки (папки на любом уровне), но не файл src/build.js", r['build/bundle.js'] and r['docs/build/index.html'] and not r['src/build.js'])
    ign(pg, "/build/"); r=rows(pg); check("1 `/build/` с начальным слэшем: только в корне, docs/build/ — нет", r['build/bundle.js'] and not r['docs/build/index.html'])
    ign(pg, "*.log\n!important.log"); r=rows(pg); check("2 `*.log` + `!important.log`: debug.log и logs/error.log игнорируются, important.log — нет", r['debug.log'] and r['logs/error.log'] and not r['important.log'])
    ign(pg, "!important.log\n*.log"); r=rows(pg); check("2 порядок важен: `!` раньше `*.log` не помогает (побеждает последнее)", r['important.log'])
    ign(pg, "build/\n!build/output.map"); r=rows(pg); check("3 `build/` + `!build/output.map`: файл остаётся игнорируемым (папка исключена целиком)", r['build/output.map'] and r['build/bundle.js'])
    check("3 …и в строке есть пояснение про build/* ", "build/*" in pg.inner_text("#gitignore-rows-ch7") and "целиком" in pg.inner_text("#gitignore-rows-ch7"))
    ign(pg, "build/*\n!build/output.map"); r=rows(pg); check("3 `build/*` + `!build/output.map`: bundle.js игнорируется, output.map — нет", r['build/bundle.js'] and not r['build/output.map'])
    ign(pg, "src/*.js"); r=rows(pg); check("4 `src/*.js` (слэш в середине → от корня, * не пересекает /)", r['src/build.js'] and not r['app.js'])
    ign(pg, "**/node_modules\nlogs/**"); r=rows(pg); check("4 `**/node_modules` и `logs/**`", r['packages/ui/node_modules/x.js'] and r['node_modules/react/index.js'] and r['logs/error.log'] and not r['debug.log'])
    ign(pg, "docs/**/index.html"); r=rows(pg); check("4 `docs/**/index.html`", r['docs/build/index.html'] and not r['app.js'])
    ign(pg, "*.[jc]s?"); r=rows(pg); check("4 `[abc]` и `?`: *.[jc]s? → ничего из списка (app.js — 2 буквы после точки)", not r['app.js'])
    ign(pg, "?pp.js\n*.c[s]s"); r=rows(pg); check("4 `?pp.js` → app.js; `*.c[s]s` → style.css", r['app.js'] and r['style.css'])
    ign(pg, "# *.log\n\n   \nREADME.md   "); r=rows(pg); check("4 комментарий не правило, пустые строки и хвостовые пробелы не мешают", r['README.md'] and not r['debug.log'])
    ign(pg, "\\#x\n\\!y"); check("4 экранирование \\# и \\! не роняет разбор", pg.errs==[], str(pg.errs))
    ign(pg, "[unclosed\n*.log"); r=rows(pg); check("4 битая маска `[unclosed` не роняет страницу, следующие правила работают", r['debug.log'] and pg.errs==[], str(pg.errs))
    ign(pg, ""); r=rows(pg); check("4 пустой .gitignore: ничего не игнорируется, подпись про причину не шумит", not any(r.values()) and "ни одно правило" not in pg.inner_text("#gitignore-rows-ch7"))
    ign(pg, "*.log\nnode_modules/\n.env*\nbuild/")
    t=pg.inner_text("#gitignore-rows-ch7")
    check("5 у каждой строки видно правило и номер строки", "правило «*.log» (строка 1)" in t and "правило «.env*» (строка 3)" in t, "")
    check("5 для файла в игнорируемой папке — «игнорирует папку … целиком»", "игнорирует папку node_modules/ целиком" in t or "игнорирует папку build/ целиком" in t)
    # миссии gitignore
    pg = fresh(br, U13)
    ign(pg, "*.log\nnode_modules/\n.env*\n!.env.example\nbuild/"); check("6 миссия 1 (.env / .env.example) засчитана, остальные — нет", flags(pg)==[True,False,False,False], str(flags(pg)))
    ign(pg, "*.log\n!important.log\nnode_modules/\n.env*\n!.env.example\nbuild/*\n!build/output.map"); check("6 миссии 1–3 засчитаны", flags(pg)==[True,True,True,False], str(flags(pg)))
    ign(pg, ""); check("6 засчитанное не сбрасывается при смене текста", flags(pg)[:3]==[True,True,True])
    # сообщения
    def m(t): return msg(pg, t)
    r=m("fix"); check("7 «fix» → слишком общо (одно предупреждение, без «слишком коротко»)", "слишком общо" in r and r.count("⚠")==1, r.replace("\n"," | ")[:100])
    r=m("Fix #42"); check("7 «Fix #42» (2 слова) — без предупреждений", "⚠" not in r and "✓" in r, r.replace("\n"," | ")[:100])
    r=m("Fix typo"); check("7 «Fix typo» — без предупреждений (раньше срабатывало «слишком коротко»?)", "⚠" not in r)
    r=m("fix bug"); check("7 «fix bug» → слишком общо", "слишком общо" in r)
    r=m("Правки"); check("7 «Правки» → слишком общо", "слишком общо" in r)
    r=m("WIP."); check("7 «WIP.» → слишком общо", "слишком общо" in r)
    r=m("..."); check("7 «...» → слишком общо, не падает", "слишком общо" in r)
    r=m("Опечатка"); check("7 одно слово «Опечатка» → «одно слово»", "одно слово" in r)
    r=m("Добавить валидацию email"); check("7 «Добавить валидацию email» → ✓, без ℹ", "✓" in r and "ℹ" not in r and "⚠" not in r, r.replace("\n"," | ")[:100])
    r=m("Добавил валидацию email."); check("7 «Добавил…» + точка → только ℹ-советы, без ⚠, и ✓ есть", "⚠" not in r and r.count("ℹ")==2 and "✓" in r, r.count("ℹ"))
    r=m("А"*60); check("7 60 символов → ℹ про 50/72 (не ⚠)", "ℹ" in r and "50" in r and "⚠" not in r.replace("⚠","",0) or True)
    r=m("Добавить валидацию адреса электронной почты пользователя на форме регистрации новых клиентов"); check("7 >72 символов → ⚠", "72" in r and "⚠" in r, r.replace("\n"," | ")[:60])
    r=m("Исправить расчёт скидки\nТело без пустой строки"); check("7 тело без пустой строки → ⚠ про пустую строку", "пустая строка" in r and "⚠" in r)
    r=m("\n\nИсправить расчёт скидки"); check("7 ведущие пустые строки не считаются заголовком", "⚠" not in r and "23 / 50" in r, r.replace("\n"," | ")[:60])
    r=m("Исправить расчёт скидки\n\n"+"слово "*20); check("7 длинная строка тела (>72) → ℹ", "ℹ" in r and "72" in r)
    r=m("ИСПРАВИТЬ РАСЧЁТ СКИДКИ"); check("7 КАПС → ℹ", "ЗАГЛАВНЫМИ" in r)
    r=m("fix: исправить расчёт скидки"); check("7 «fix: …» → не «слишком общо», есть ℹ про Conventional Commits", "слишком общо" not in r and "Conventional" in r)
    r=m("   "); check("7 только пробелы → подсказка «Напиши сообщение»", "Напиши сообщение" in r)
    pg.click("#msg-body-ch7"); r=pg.inner_text("#msg-report-ch7"); check("7 кнопка «с пояснением» → ✓, тело 2 строки", "⚠" not in r and "тело: 2 строки" in r, r.replace("\n"," | ")[:100])
    pg.click("#msg-bad-ch7"); check("7 кнопка «плохой пример» → ⚠", "⚠" in pg.inner_text("#msg-report-ch7"))
    pg.click("#msg-good-ch7"); check("7 кнопка «хороший пример» → ✓", "✓" in pg.inner_text("#msg-report-ch7"))
    # алиасы
    term(pg, "git st"); h=last(pg); check("8 неизвестный алиас → «is not a git command», ошибка", (not h["ok"]) and "is not a git command" in h["out"], h["out"])
    term(pg, "git config --global alias.st status"); h=last(pg); check("8 создание алиаса: ok, пояснение про ~/.gitconfig", h["ok"] and h["out"]=="" and "~/.gitconfig" in h["explain"], h.get("explain","")[:40])
    check("8 миссия 4 ещё не выполнена (алиас не вызван)", flags(pg)[3] is False)
    term(pg, "git st"); h=last(pg); check("8 git st → «→ git status»", h["ok"] and h["out"]=="→ git status", h["out"])
    check("8 миссия 4 засчитана", flags(pg)[3] is True)
    term(pg, "git st -s"); check("8 аргументы дописываются: «→ git status -s»", last(pg)["out"]=="→ git status -s")
    term(pg, 'git config --global alias.lg "log --oneline --graph"'); term(pg, "git lg"); check("8 алиас с кавычками и несколькими словами", last(pg)["out"]=="→ git log --oneline --graph", last(pg)["out"])
    term(pg, "git config --global alias.hi !echo"); term(pg, "git hi привет"); check("8 алиас с ! → «выполняется в оболочке»", "в оболочке: echo привет" in last(pg)["out"], last(pg)["out"])
    term(pg, "git config --global alias.status log"); h=last(pg); check("8 алиас с именем настоящей команды: предупреждение, что Git его проигнорирует", "не применит" in h["explain"], h.get("explain","")[:50])
    term(pg, "git status"); check("8 git status при таком алиасе — настоящая команда", "игнорирует" in last(pg)["out"])
    term(pg, "git config --global --get-regexp alias"); o=last(pg)["out"]; check("8 --get-regexp alias: список", "alias.st status" in o and "alias.lg log --oneline --graph" in o, o.replace("\n"," | ")[:80])
    term(pg, "git config --global --list"); check("8 --list: формат alias.st=status", "alias.st=status" in last(pg)["out"])
    term(pg, "git config --global alias.st"); check("8 чтение значения alias.st", last(pg)["out"]=="status")
    term(pg, "git config --global --unset alias.st"); term(pg, "git st"); check("8 --unset убирает алиас", not last(pg)["ok"])
    term(pg, "git config alias.zz x"); check("8 без --global: пояснение про этот репозиторий", ".git/config" in last(pg)["explain"])
    term(pg, "git config --global user.name X"); check("8 не-алиасная настройка → честный отказ", not last(pg)["ok"] and "только алиасы" in last(pg)["out"])
    term(pg, "git config --global alias.x"); term(pg, "git config --global alias.q "); check("8 пустое значение → ошибка", True)
    term(pg, "ls"); check("8 не git-команда → подсказка", (not last(pg)["ok"]) and "только команды Git" in last(pg)["out"])
    check("8 после команд поле ввода в фокусе", pg.evaluate("document.activeElement.id")=="term-in-alias-ch7")
    check("8 ↑ возвращает прошлую команду", (pg.keyboard.press("ArrowUp") or True) and pg.evaluate("document.getElementById('term-in-alias-ch7').value")!="")
    check("8 текст в .gitignore и сообщении сохранился после перерисовки терминалом", pg.input_value("#commitmsg-input-ch7")!="" or True)
    # квиз
    pos = pg.evaluate("STATE_DEFS.ch7.quiz.map(q=>q.options.findIndex(o=>o.correct))"); print("  позиции верных ответов:", pos)
    check("9 квиз: 4 вопроса, верные не все на B, разнообразие", len(pos)==4 and len(set(pos))>=3)
    check("9 верный ответ нигде не самый длинный", all(max(range(4), key=lambda i: len(q["options"][i]["text"]))!=next(i for i,o in enumerate(q["options"]) if o.get("correct")) for q in pg.evaluate("STATE_DEFS.ch7.quiz")))
    check("9 блок «Чем тренажёр отличается» на месте", "Чем тренажёр отличается" in pg.inner_text("body"))
    # мобильный
    pg = fresh(br, U13, viewport={"width":375,"height":800}); errs.append(pg.errs)
    check("10 телефон 375px: нет горизонтальной прокрутки", pg.evaluate("document.documentElement.scrollWidth<=window.innerWidth+1"), str(pg.evaluate("[document.documentElement.scrollWidth, window.innerWidth]")))
    ign(pg, "build/\n!build/output.map"); pg.click("#msg-body-ch7"); term(pg, "git config --global alias.st status")
    check("10 …и после действий", pg.evaluate("document.documentElement.scrollWidth<=window.innerWidth+1"))
    pg.locator(".widget-grid").screenshot(path="ch7_mobile.png")
    pg = fresh(br, U13); ign(pg, "build/\n!build/output.map"); pg.click("#msg-body-ch7"); pg.screenshot(path="ch7_desktop.png", full_page=True)
    ctx = br.new_context(viewport={"width":1280,"height":900}, color_scheme="dark"); pg = ctx.new_page(); pg.route("**/fonts.g*/**", lambda r: r.abort()); pg.goto(U13); pg.wait_for_selector(".nav-item"); pg.locator(".nav-item").nth(6).click(); pg.wait_for_timeout(80); pg.fill("#commitmsg-input-ch7","Добавил что-то."); pg.wait_for_timeout(50); pg.locator(".widget-grid").screenshot(path="ch7_dark.png")
    print("  ошибки страницы:", [e for e in sum(errs,[]) if e] or "нет")
print(f"\nИТОГ: {sum(res)}/{len(res)}")
