exec(open("p3.py").read().split("with sync_playwright")[0])
U13="file:///mnt/user-data/outputs/git-trenazher_13.html"; U14="file:///mnt/user-data/outputs/git-trenazher_15.html"
R = "STATE.chapters.appx.repo"
def new(br, url): pg = fresh(br, url); nav(pg, 7); return pg
def c8(pg, t): cmd(pg, "appx", t); return H(pg, "appx")
def ed(pg, f="app.js"): pg.locator(f"[data-fileop=edit][data-file='{f}']").click(); pg.wait_for_timeout(60)
def flags(pg): return pg.eval_on_selector_all(".mission", "els => els.map(e => e.classList.contains('done'))")
def msgs(pg, ref): return pg.evaluate(f"{R}.log({{ref:{json.dumps(ref)}}}).map(c=>c.message)")
def ids(pg, ref): return pg.evaluate(f"{R}.log({{ref:{json.dumps(ref)}}}).map(c=>c.id)")
def ncommits(pg): return pg.evaluate(f"Object.keys({R}.commits).length")
def ghosts(pg): return pg.locator('.graph-wrap circle[stroke-dasharray="3 2"]').count()
def cid(pg, part): return pg.evaluate(f"Object.values({R}.commits).find(c=>c.message.includes({json.dumps(part)})).id.slice(0,7)")
with sync_playwright() as p:
    br = p.chromium.launch(args=["--no-sandbox"]); errs=[]
    print("=== ДО (_13) ===")
    pg = new(br, U13); c8(pg,"git tag v1"); h=c8(pg,"git tag v1"); print("  повторный git tag v1: ok =", h["ok"], "| 💡", h["explain"][:40])
    h=c8(pg,"git tag -a v2 -m x"); print("  git tag -a v2 -m x:", h["ok"], h["out"][:40].replace("\n"," "))
    pg = new(br, U13); c8(pg,"git checkout feature"); c8(pg,"git rebase master"); n1=ncommits(pg); c8(pg,"git rebase master"); print("  feature=1 коммит; rebase master дважды: коммитов в репозитории было/стало:", n1, ncommits(pg), "| второй вывод:", H(pg,'appx')['out'], "| призраков:", ghosts(pg))
    pg = new(br, U13); h=c8(pg,"git log --oneline --all"); print("  git log --all:", h["ok"])
    print("\n=== ПОСЛЕ (_14) ===")
    # --- теги
    pg = new(br, U14); errs.append(pg.errs)
    check("0 миссии: 7, ни одна не выполнена", flags(pg)==[False]*7, str(flags(pg)))
    h=c8(pg,"git tag v1.0.0"); check("1 лёгкий тег: ok, 💡 «лёгкая метка»", h["ok"] and h["out"]=="" and "лёгкая" in h["explain"], h.get("explain","")[:40])
    h=c8(pg,"git tag v1.0.0"); check("1 повторный тег → fatal: already exists + 💡, метка не перезаписана", (not h["ok"]) and "already exists" in h["out"] and "не даёт молча" in h["explain"])
    h=c8(pg,'git tag -a v1.1.0 -m "Релиз"'); check("1 аннотированный тег -a -m: ok, 💡 про сообщение и git show", h["ok"] and "git show" in h["explain"], h.get("explain","")[:40])
    h=c8(pg,'git tag -am "Кандидат" v1.2.0-rc'); check("1 -am в кластере: тег создан", h["ok"] and pg.evaluate(f"{R}.tagMeta['v1.2.0-rc'].message")=="Кандидат", h["out"])
    h=c8(pg,'git tag -m "Только сообщение" v1.3.0'); check("1 -m без -a → тоже аннотированный (как в Git)", h["ok"] and pg.evaluate(f"'v1.3.0' in {R}.tagMeta"))
    h=c8(pg,'git tag --annotate v1.4.0 --message "Длинные флаги"'); check("1 --annotate / --message", h["ok"] and pg.evaluate(f"{R}.tagMeta['v1.4.0'].message")=="Длинные флаги")
    h=c8(pg,"git tag -a v1.5.0"); check("1 -a без -m → понятный отказ (редактора нет)", (not h["ok"]) and "-m" in h["out"] and "редактор" in h["explain"] and pg.evaluate(f"!('v1.5.0' in {R}.tags)"), h["out"][:50])
    h=c8(pg,"git tag -m"); check("1 -m без значения → ошибка", not h["ok"] and "requires a value" in h["out"])
    h=c8(pg,"git tag"); check("1 git tag: список по алфавиту", h["out"].split("\n")==sorted(h["out"].split("\n")) and len(h["out"].split("\n"))==5, h["out"].replace("\n"," "))
    check("1 …и 💡 «по алфавиту»", "по алфавиту" in h["explain"])
    h=c8(pg,'git tag -l "v1.*"'); check("1 git tag -l с маской v1.*", len(h["out"].split("\n"))==5 and h["ok"])
    h=c8(pg,"git tag -l v1.1*"); check("1 маска v1.1* → v1.1.0", h["out"]=="v1.1.0", h["out"])
    h=c8(pg,"git tag -l nosuch*"); check("1 маска без совпадений → пусто, ok", h["ok"] and h["out"]=="")
    h=c8(pg,"git tag --list"); check("1 --list", h["ok"] and "v1.0.0" in h["out"])
    h=c8(pg,"git tag -f v1.0.0 HEAD~0"); check("1 -f переставляет: «Updated tag … (was …)» + 💡", h["ok"] and h["out"].startswith("Updated tag 'v1.0.0' (was ") and "переставлен" in h["explain"], h["out"])
    h=c8(pg,"git tag -d v1.0.0"); check("1 -d: Deleted tag … (was …), 💡", h["ok"] and h["out"].startswith("Deleted tag 'v1.0.0' (was ") and "исчезла только метка" in h["explain"], h["out"])
    h=c8(pg,"git tag -d v1.0.0"); check("1 -d несуществующего → error: not found + 💡", (not h["ok"]) and "not found" in h["out"] and "Такого тега нет" in h["explain"])
    h=c8(pg,"git tag -d"); check("1 -d без имени → подсказка", not h["ok"])
    for bad in ["a b", "-x", "v1..2", "v1.", "x~1", "v:1", "v?"]:
        h=c8(pg,f'git tag "{bad}"' if " " in bad else f"git tag {bad}")
    h=c8(pg,'git tag "a b"'); check("1 имя с пробелом → not a valid tag name + 💡", (not h["ok"]) and "not a valid tag name" in h["out"] and "нельзя пробелы" in h["explain"], h["out"])
    h=c8(pg,"git tag v1..2"); check("1 имя с «..» → невалидно", not h["ok"] and "not a valid tag name" in h["out"])
    h=c8(pg,"git tag x~1"); check("1 имя с «~» → невалидно", not h["ok"] and "not a valid tag name" in h["out"])
    h=c8(pg,"git tag v9 nosuch"); check("1 тег на несуществующий коммит → Failed to resolve", not h["ok"] and "Failed to resolve" in h["out"])
    h=c8(pg,"git tag v1.0.0 HEAD~1"); check("1 тег на HEAD~1 (после -d имя свободно)", h["ok"])
    h=c8(pg,"git tag a b c"); check("1 слишком много аргументов", not h["ok"] and "too many" in h["out"])
    h=c8(pg,"git tag -z"); check("1 неизвестный флаг → отказ со списком доступных", not h["ok"] and "-a" in h["out"] and "-d" in h["out"])
    h=c8(pg,"git show v1.1.0"); check("1 git show аннотированного тега: заголовок tag, сообщение, commit", h["ok"] and h["out"].startswith("tag v1.1.0\n\nРелиз\n\ncommit"), h["out"][:40].replace("\n"," "))
    h=c8(pg,"git show v1.0.0"); check("1 git show лёгкого тега: без «tag …»", h["ok"] and h["out"].startswith("commit"))
    h=c8(pg,"git log --oneline"); check("1 git log --oneline: подписи (HEAD -> master, tag: …)", "(HEAD -> master, tag: v1.1.0" in h["out"].split("\n")[0], h["out"].split("\n")[0][:80])
    check("1 …и тег на предыдущем коммите виден там же", "tag: v1.0.0" in h["out"].split("\n")[1] , h["out"].split("\n")[1][:60])
    h=c8(pg,"git log -1"); check("1 git log (не oneline) — подписи в строке commit", "(HEAD -> master, tag:" in h["out"].split("\n")[0], h["out"].split("\n")[0][:60])
    h=c8(pg,"git checkout v1.1.0"); check("1 checkout тега → detached HEAD", h["ok"] and "detached" in h["out"])
    h=c8(pg,"git log --oneline"); check("1 на detached: подпись HEAD (без ->)", "(HEAD," in h["out"].split("\n")[0] or "(HEAD)" in h["out"].split("\n")[0], h["out"].split("\n")[0][:60]); c8(pg,"git checkout master")
    check("1 граф: подпись tag:… есть", pg.evaluate("[...document.querySelectorAll('.graph-wrap text')].some(t=>t.textContent.includes('tag:v1.1.0'))"))
    # миссии тегов
    pg = new(br, U14); errs.append(pg.errs); c8(pg,"git tag v1"); check("1 миссия 1 (лёгкий тег любого имени) засчитана, 2 — нет", flags(pg)[:2]==[True,False], str(flags(pg)[:2]))
    c8(pg,'git tag -a v2 -m "Релиз"'); check("1 аннотированный без git show — миссия 2 ещё нет", flags(pg)[1] is False)
    c8(pg,"git show v2"); check("1 после git show <тег> — миссия 2 засчитана", flags(pg)[1] is True)
    pg = new(br, U14); c8(pg,'git tag -a v2 -m "Релиз"'); c8(pg,"git show HEAD"); check("1 git show HEAD (не тег) не засчитывает миссию 2", flags(pg)[1] is False)
    pg = new(br, U14); c8(pg,'git tag -a v2 -m "Релиз"'); c8(pg,"git tag v1"); check("1 миссия 1 не засчитывается лёгким тегом, если… (v1 лёгкий — да)", flags(pg)[0] is True)
    # --- stash
    pg = new(br, U14); errs.append(pg.errs)
    h=c8(pg,"git stash"); check("2 stash без правок → No local changes + 💡", (not h["ok"]) and "No local changes" in h["out"] and "Прятать нечего" in h["explain"])
    ed(pg); h=c8(pg,"git stash"); check("2 stash: «WIP on master: <хэш> <сообщение>»", h["ok"] and re.match(r"Saved working directory and index state WIP on master: [0-9a-f]{7} Добавить README", h["out"]) is not None if (re:=__import__('re')) else 0, h["out"])
    h=c8(pg,"git stash list"); check("2 stash list: формат stash@{0}: WIP on master: …", h["out"].startswith("stash@{0}: WIP on master: ") and "стопка" in h["explain"].lower() or "Стопка" in h["explain"], h["out"])
    ed(pg); h=c8(pg,'git stash -m "вторая правка"'); check("2 stash -m: «On master: вторая правка»", h["ok"] and "On master: вторая правка" in h["out"], h["out"])
    h=c8(pg,"git stash list"); check("2 в списке 2 тайника, свежий сверху", h["out"].split("\n")[0]=="stash@{0}: On master: вторая правка" and h["out"].split("\n")[1].startswith("stash@{1}: WIP"), h["out"].replace("\n"," | "))
    h=c8(pg,"git stash apply"); check("2 apply: ok, правка вернулась, тайники остались (2)", h["ok"] and "modified" in h["out"] and pg.evaluate(f"{R}.stashes.length")==2 and "остался в стопке" in h["explain"], h["out"].replace("\n"," | ")[:80])
    h=c8(pg,"git stash apply"); check("2 apply поверх своих правок → отказ, тайники целы", (not h["ok"]) and pg.evaluate(f"{R}.stashes.length")==2, h["out"][:50])
    pg.evaluate(f"{R}.working['app.js']={R}._tree({R}._headCommitId())['app.js']"); pg.evaluate(f"{R}.index['app.js']={R}._tree({R}._headCommitId())['app.js']")
    h=c8(pg,"git stash drop stash@{1}"); check("2 drop stash@{1}: удалён именно он (остался «вторая правка»)", h["ok"] and h["out"]=="Dropped stash@{1}" and pg.evaluate(f"{R}.stashList()")==["stash@{0}: On master: вторая правка"] and "нельзя" in h["explain"], h["out"])
    h=c8(pg,"git stash drop stash@{5}"); check("2 drop несуществующего → not a valid reference + 💡", (not h["ok"]) and "not a valid reference" in h["out"] and "нет такого тайника" in h["explain"])
    h=c8(pg,"git stash pop stash@x"); check("2 плохой аргумент pop → not a stash-like commit", not h["ok"] and "stash-like" in h["out"])
    h=c8(pg,"git stash pop"); check("2 pop: Dropped stash@{0}, стопка пуста", h["ok"] and h["out"]=="Dropped stash@{0}" and pg.evaluate(f"{R}.stashes.length")==0)
    h=c8(pg,"git stash pop"); check("2 pop из пустой стопки → No stash entries found + 💡", (not h["ok"]) and "No stash entries" in h["out"] and "нет такого тайника" in h["explain"])
    h=c8(pg,"git stash drop"); check("2 drop из пустой → No stash entries", not h["ok"])
    ed(pg); c8(pg,"git stash"); h=c8(pg,"git stash clear"); check("2 clear: стопка очищена, 💡", h["ok"] and pg.evaluate(f"{R}.stashes.length")==0 and "очищена" in h["explain"])
    h=c8(pg,"git stash -u"); check("2 stash -u → честный отказ (не поддерживается)", (not h["ok"]) and "-u" in h["out"] and "не поддерживает" in h["out"])
    h=c8(pg,"git stash show"); check("2 stash show → «не поддерживается» + список доступных", not h["ok"] and "не поддерживается" in h["out"] and "apply" in h["out"])
    ed(pg); h=c8(pg,"git stash push -m msg"); check("2 stash push -m по-прежнему работает", h["ok"] and "On master: msg" in h["out"], h["out"])
    ed(pg); h=c8(pg,'git stash save "старый стиль"'); check("2 stash save \"текст\"", h["ok"] and "On master: старый стиль" in h["out"], h["out"])
    # LIFO
    pg = new(br, U14); ed(pg); c8(pg,"git stash"); pg.evaluate(f"{R}.working['app.js']='вторая версия'"); c8(pg,'git stash -m второй'); c8(pg,"git stash pop")
    check("2 LIFO: pop вернул ПОСЛЕДНИЙ тайник (вторая версия), а первый остался", pg.evaluate(f"{R}.working['app.js']")=="вторая версия" and pg.evaluate(f"{R}.stashes.length")==1)
    # --- log --all
    pg = new(br, U14); errs.append(pg.errs)
    h=c8(pg,"git log --oneline"); check("3 log --oneline на master: 2 коммита + базовый = 2 (README + база), без feature", len(h["out"].split("\n"))==2 and "fix" not in h["out"], h["out"].replace("\n"," | "))
    h=c8(pg,"git log --oneline --all"); check("3 log --all: все 4 коммита, в подписях feature", len(h["out"].split("\n"))==4 and "feature" in h["out"] and "fix: опечатка" in h["out"], h["out"].replace("\n"," | "))
    # --- rebase
    pg = new(br, U14); errs.append(pg.errs); ch1 = ncommits(pg); c8(pg,"git checkout feature"); before = ids(pg,"feature")
    h=c8(pg,"git rebase master"); after = ids(pg,"feature")
    check("4 rebase feature на master: ok, «Successfully rebased»", h["ok"] and "Successfully rebased and updated refs/heads/feature." in h["out"], h["out"])
    check("4 …2 своих коммита получили НОВЫЕ ID, README теперь в истории feature", len(after)==4 and set(after[:2]).isdisjoint(before) and "Добавить README" in msgs(pg,"feature"), str(msgs(pg,"feature")))
    check("4 …порядок сообщений сохранён, файлы: README.md, about.html, app.js правка", msgs(pg,"feature")[:2]==["Добавить страницу «О проекте»","fix: опечатка в логе"] and pg.evaluate(f"Object.keys({R}.working).sort().join()")=="README.md,about.html,app.js")
    check("4 …на графе бледные старые коммиты (2 призрака)", ghosts(pg)==2, str(ghosts(pg)))
    check("4 …💡: новые ID, старые бледные", "новые ID" in h["explain"] and "бледными" in h["explain"], h["explain"][:60])
    n = ncommits(pg); h=c8(pg,"git rebase master")
    check("4 повторный rebase → «Current branch feature is up to date.», новых коммитов нет, ID те же", h["ok"] and h["out"]=="Current branch feature is up to date." and ncommits(pg)==n and ids(pg,"feature")==after and "прежними ID" in h["explain"], h["out"])
    h=c8(pg,"git log --oneline --all"); check("4 история линейна: master + feature подписи, 4+2 коммита", h["ok"] and "(HEAD -> feature" in h["out"], h["out"].replace("\n"," | ")[:100])
    # ff
    pg = new(br, U14); errs.append(pg.errs); c8(pg,"git branch topic"); ed(pg,"README.md"); c8(pg,"git add README.md"); c8(pg,'git commit -m "README 2"'); c8(pg,"git checkout topic"); h=c8(pg,"git rebase master")
    check("4 ветка без своих коммитов: fast-forward-вариант, 💡 «просто сдвинулась»", h["ok"] and "Successfully rebased" in h["out"] and "просто сдвинулась" in h["explain"] and msgs(pg,"topic")[0]=="README 2", h["out"])
    # rebase master onto feature (master имеет README)
    pg = new(br, U14); errs.append(pg.errs); h=c8(pg,"git rebase feature")
    check("4 rebase master на feature: перенёс README поверх feature, ID README новый", h["ok"] and msgs(pg,"master")[0]=="Добавить README" and len(msgs(pg,"master"))==4, str(msgs(pg,"master")))
    # cherry-pick + rebase: дубликат пропускается
    pg = new(br, U14); errs.append(pg.errs); fixid=cid(pg,"fix: опечатка"); c8(pg,f"git cherry-pick {fixid}"); c8(pg,"git checkout feature"); h=c8(pg,"git rebase master")
    m=msgs(pg,"feature")
    check("5 после cherry-pick: rebase пропускает дубликат: warning: skipped previously applied commit", h["ok"] and f"skipped previously applied commit {fixid}" in h["out"], h["out"])
    check("5 …в истории feature ровно ОДИН «fix: опечатка» (без дубля) и «О проекте» сверху", m.count("fix: опечатка в логе")==1 and m[0]=="Добавить страницу «О проекте»" and len(m)==4, str(m))
    check("5 …💡 про пропущенный дубликат", "пропустил" in h["explain"] and "cherry-pick" in h["explain"], h["explain"][:80])
    # конфликт
    pg = new(br, U14); errs.append(pg.errs); pg.evaluate(f"{R}.working['app.js']='console.log(\"master\");'"); c8(pg,"git add app.js"); c8(pg,'git commit -m "master правит app.js"'); c8(pg,"git checkout feature")
    n=ncommits(pg); b=pg.evaluate(f"JSON.stringify({R}.branches)"); w=pg.evaluate(f"JSON.stringify({R}.working)"); h=c8(pg,"git rebase master")
    check("6 конфликт: отказ, CONFLICT в app.js, понятно что тренажёр не продолжает", (not h["ok"]) and "CONFLICT" in h["out"] and "--continue" in h["out"] and "git merge master" in h["out"], h["out"].splitlines()[1])
    check("6 …ничего не изменено: ветки, файлы, число коммитов, нет призраков", pg.evaluate(f"JSON.stringify({R}.branches)")==b and pg.evaluate(f"JSON.stringify({R}.working)")==w and ncommits(pg)==n and ghosts(pg)==0 and pg.evaluate(f"!{R}.conflict"))
    check("6 …💡 про конфликт", "остановился бы на конфликте" in h["explain"])
    h=c8(pg,"git merge master"); check("6 merge того же — даёт обычный конфликт (альтернатива работает)", (not h["ok"]) and "CONFLICT" in h["out"])
    # dirty
    pg = new(br, U14); errs.append(pg.errs); c8(pg,"git checkout feature"); ed(pg); n=ncommits(pg); h=c8(pg,"git rebase master")
    check("7 rebase с несохранёнными правками → отказ, коммитов не прибавилось", (not h["ok"]) and "cannot rebase" in h["out"] and ncommits(pg)==n)
    h=c8(pg,"git rebase nosuch"); check("7 rebase несуществующей ветки", not h["ok"] and "no such branch" in h["out"])
    h=c8(pg,"git rebase"); check("7 rebase без аргумента → usage", not h["ok"] and "usage" in h["out"])
    # detached rebase
    pg = new(br, U14); errs.append(pg.errs); c8(pg,f"git checkout {cid(pg,'fix: опечатка')}"); h=c8(pg,"git rebase master")
    check("7 rebase из detached HEAD: не падает, HEAD перемещён", h["ok"] and pg.evaluate(f"{R}.HEAD.type")=="detached" and pg.errs==[], h["out"])
    # --- reflog / reset
    pg = new(br, U14); errs.append(pg.errs); c8(pg,"git cherry-pick "+cid(pg,'fix: опечатка')); c8(pg,"git reset --hard HEAD~1")
    check("8 после reset --hard HEAD~1: cherry-pick-коммит пропал из log, есть призрак", "fix: опечатка в логе" not in msgs(pg,"master") and ghosts(pg)>=1)
    h=c8(pg,"git reset --hard HEAD~1"); c8(pg,"git reset --hard HEAD@{1}") ; h=H(pg,"appx")
    check("8 reset --hard HEAD@{n} возвращает ветку, 💡 про reflog", h["ok"] and "reflog" in h["explain"] and "спасают" in h["explain"], h["explain"][:60])
    h=c8(pg,"git reset --hard HEAD~1"); check("8 reset --hard HEAD~1: 💡 про бледные коммиты и reflog", "бледными" in h["explain"] and "reflog" in h["explain"])
    h=c8(pg,"git reflog"); check("8 reflog: 💡 про HEAD@{1}", "HEAD@{1}" in h["explain"])
    # --- сквозной сценарий по миссиям
    pg = new(br, U14); errs.append(pg.errs)
    c8(pg,"git tag v1.0.0"); c8(pg,'git tag -a v1.1.0 -m "Релиз"'); c8(pg,"git show v1.1.0")
    ed(pg); c8(pg,"git stash"); c8(pg,"git stash pop")
    c8(pg,"git log --oneline feature"); c8(pg,"git checkout -- app.js"); c8(pg,f"git cherry-pick {cid(pg,'fix: опечатка')}")
    check("9 сквозной сценарий: миссии 1–5 засчитаны, 6–7 ещё нет", flags(pg)==[True]*5+[False]*2, str(flags(pg)))
    c8(pg,"git reset --hard HEAD~1"); c8(pg,"git reflog"); c8(pg,"git reset --hard HEAD@{1}"); check("9 после reflog-спасения — миссия 6", flags(pg)[5] is True, str(flags(pg)))
    c8(pg,"git checkout feature"); h=c8(pg,"git rebase master"); check("9 rebase после cherry-pick: миссия 7 засчитана", flags(pg)==[True]*7 and h["ok"] and "skipped" in h["out"], str(flags(pg)))
    pg = new(br, U14); c8(pg,"git checkout feature"); c8(pg,"git rebase master"); c8(pg,"git rebase master"); check("9 повторный «up to date» rebase не считается за миссию 7 (нужен настоящий перенос)", flags(pg)[6] is True)  # первый rebase настоящий
    pg = new(br, U14); c8(pg,"git checkout feature"); c8(pg,"git rebase feature"); check("9 «up to date» rebase (feature на feature) миссию 7 не закрывает", flags(pg)[6] is False, str(flags(pg)))
    # --- др. главы: log без подписей
    pg = fresh(br, U14); nav(pg, 3); cmd(pg, "ch4", "git log --oneline"); o = H(pg,"ch4")["out"]; check("10 в разделе 4 подписей в git log нет (изменения только в разделе 8)", "(" not in o.split("\n")[0].split(" ",1)[0] and "HEAD ->" not in o, o.split("\n")[0])
    # --- квиз
    pg = new(br, U14); errs.append(pg.errs); pos = pg.evaluate("STATE_DEFS.appx.quiz.map(q=>q.options.findIndex(o=>o.correct))"); print("  позиции верных ответов:", pos)
    check("11 квиз: 5 вопросов, верные ответы разнесены", len(pos)==5 and len(set(pos))>=3 and pos.count(1)<=1)
    check("11 верный ответ нигде не самый длинный", all(max(range(4), key=lambda i: len(q["options"][i]["text"]))!=next(i for i,o in enumerate(q["options"]) if o.get("correct")) for q in pg.evaluate("STATE_DEFS.appx.quiz")))
    check("11 блок «Чем тренажёр отличается» на месте", "Чем тренажёр отличается" in pg.inner_text("body"))
    # мобильный
    pg = fresh(br, U14, viewport={"width":375,"height":800}); nav(pg, 7); errs.append(pg.errs); c8(pg,'git tag -a v1 -m "x"'); c8(pg,"git log --oneline --all")
    check("12 телефон 375px: нет горизонтальной прокрутки", pg.evaluate("document.documentElement.scrollWidth<=window.innerWidth+1"), str(pg.evaluate("[document.documentElement.scrollWidth, window.innerWidth]")))
    print("  ошибки страницы:", [e for e in sum(errs,[]) if e] or "нет")
print(f"\nИТОГ: {sum(res)}/{len(res)}")
