exec(open("p3.py").read().split("with sync_playwright")[0])
U6="file:///mnt/user-data/outputs/git-trenazher_6.html"; U7="file:///mnt/user-data/outputs/git-trenazher_15.html"
def flags(pg): return pg.eval_on_selector_all(".mission", "els => els.map(e => e.classList.contains('done'))")
def c2(pg, t): cmd(pg, "ch2", t)
def edit2(pg): edit(pg, 0)
def happy(pg):
    for t in ["git branch dark-theme", "git checkout dark-theme"]: c2(pg, t)
    edit2(pg); c2(pg, "git add style.css"); c2(pg, 'git commit -m "тема"')
def H2(pg): return H(pg, "ch2")
with sync_playwright() as p:
    br = p.chromium.launch(args=["--no-sandbox"])
    print("=== ДО (_6): воспроизведение ===")
    pg = fresh(br, U6); nav(pg, 1); happy(pg); f1 = flags(pg); c2(pg, "git checkout master"); f2 = flags(pg)
    print("  миссии после коммита в dark-theme:", f1, "→ после checkout master:", f2)
    pg = fresh(br, U6); nav(pg, 1); c2(pg, "git checkout -b dark-theme"); print("  checkout -b dark-theme:", flags(pg))
    pg = fresh(br, U6); nav(pg, 1); c2(pg, "git checkout master"); c2(pg, "git merge master"); print("  без работы, `checkout master` + `merge master`:", flags(pg), "| 💡", H2(pg).get("explain"))
    pg = fresh(br, U6); nav(pg, 1); edit2(pg); pg.locator("#demo-ch2").click(); pg.wait_for_timeout(80)
    print("  демо с правкой в файле: коммиты", pg.evaluate("Object.values(STATE.chapters.ch2.repo.commits).map(c=>c.message)"))

    print("\n=== ПОСЛЕ (_7) ===")
    errs=[]
    pg = fresh(br, U7); errs.append(pg.errs); nav(pg, 1)
    check("теория: «одни и те же строки»", "одни и те же строки" in pg.inner_text(".theory-block"))
    check("рамка «Чем тренажёр отличается» есть", "Чем тренажёр отличается" in pg.inner_text("#content"))
    check("в панели файлов виден текст style.css", pg.locator(".file-preview").count() == 1 and "background" in pg.locator(".file-preview").first.inner_text())
    happy(pg); f1 = flags(pg); check("после коммита в dark-theme: миссии 1–3 выполнены, 4–5 нет", f1 == [True, True, True, False, False], str(f1))
    c2(pg, "git checkout master"); f2 = flags(pg); check("после checkout master миссия 3 НЕ снимается, миссия 4 выполнена", f2 == [True, True, True, True, False], str(f2))
    c2(pg, "git merge dark-theme"); f3 = flags(pg); check("после merge все 5 миссий", all(f3) and "Fast-forward" in H2(pg)["out"], str(f3))
    c2(pg, "git checkout dark-theme"); check("после ухода на другую ветку миссии остаются", all(flags(pg)))
    # -b
    pg = fresh(br, U7); errs.append(pg.errs); nav(pg, 1); c2(pg, "git checkout -b dark-theme")
    check("checkout -b dark-theme засчитывает миссии 1 и 2", flags(pg)[:2] == [True, True], str(flags(pg)))
    # ложные срабатывания
    pg = fresh(br, U7); errs.append(pg.errs); nav(pg, 1); c2(pg, "git checkout master")
    h = H2(pg); check("checkout master на master → Already on 'master', пояснение", h["ok"] and h["out"] == "Already on 'master'" and "уже на этой ветке" in (h.get("explain") or ""), h["out"])
    check("…и миссия 4 не засчитана (ещё нет коммита в dark-theme)", flags(pg)[3] is False, str(flags(pg)))
    check("…reflog не пополнился записью checkout", pg.evaluate("STATE.chapters.ch2.repo.reflog.filter(e=>e.action==='checkout').length") == 0)
    c2(pg, "git merge master"); h = H2(pg)
    check("merge master на master: пояснение про «нечего сливать», а не «ветки разошлись»", "Сливать нечего" in (h.get("explain") or "") and "разошлись" not in h["explain"], h.get("explain", "")[:60])
    check("…и миссия 5 не засчитана", flags(pg)[4] is False, str(flags(pg)))
    c2(pg, "git branch dark-theme"); c2(pg, "git merge dark-theme")
    check("merge ветки без своих коммитов миссию 5 не засчитывает", flags(pg)[4] is False)
    # checkout -- file
    edit2(pg); c2(pg, "git checkout -- style.css"); h = H2(pg)
    check("checkout -- файл: пояснение про потерю правок (а не «переключился на ветку»)", "безвозвратно" in (h.get("explain") or "") and "HEAD переключился" not in h["explain"], h.get("explain", "")[:70])
    edit2(pg); c2(pg, "git checkout master"); c2(pg, "git checkout dark-theme")
    c2(pg, "git checkout master"); edit2(pg); c2(pg, "git branch feat"); c2(pg, "git checkout feat"); h = H2(pg)
    # конфликт
    pg = fresh(br, U7); errs.append(pg.errs); nav(pg, 1)
    pg.locator("#demo-ch2").click(); pg.wait_for_timeout(80); c2(pg, "git merge conflict-demo"); h = H2(pg)
    check("конфликт: пояснение про метки и подсветку", (not h["ok"]) and "метки конфликта" in (h.get("explain") or ""), h.get("explain", "")[:60])
    check("метки <<<<<<<, =======, >>>>>>> видны в панели файлов и подсвечены (3 строки)", pg.locator(".file-preview .conf-mark").count() == 3, str(pg.locator(".file-preview .conf-mark").all_inner_texts()))
    check("в предпросмотре есть обе версии правки", "сузили отступы" in pg.inner_text(".file-preview") and "увеличили шрифт" in pg.inner_text(".file-preview"))
    pg.locator("[data-resolve=both]").click(); pg.wait_for_timeout(80)
    check("после разрешения меток в файле нет", pg.locator(".file-preview .conf-mark").count() == 0)
    c2(pg, 'git commit -m "слияние"'); check("после разрешения commit проходит", H2(pg)["ok"])
    # демо с чужими правками
    pg = fresh(br, U7); errs.append(pg.errs); nav(pg, 1); edit2(pg); pg.locator("#demo-ch2").click(); pg.wait_for_timeout(80)
    check("демо при несохранённых правках не создаёт ветку и коммиты", "conflict-demo" not in branches(pg, "ch2") and pg.evaluate("Object.keys(STATE.chapters.ch2.repo.commits).length") == 1)
    note = pg.evaluate("(()=>{const h=STATE.chapters.ch2.hist; return h[h.length-1].text})()")
    check("…в терминал выведено понятное объяснение", "незакоммиченные" in note, note[:80])
    pg.locator("[data-fileop=edit]").first.click()  # ещё правка не мешает
    c2(pg, "git add style.css"); c2(pg, 'git commit -m "своя правка"')
    pg.locator("#demo-ch2").click(); pg.wait_for_timeout(80)
    check("после коммита демо запускается", "conflict-demo" in branches(pg, "ch2"))
    check("свои правки в демо-коммиты не попали", not any("dark" in c["message"] for c in [] ) and pg.evaluate("Object.values(STATE.chapters.ch2.repo.commits).filter(c=>c.message.startsWith('conflict-demo')).length") == 1)
    # квиз
    pg = fresh(br, U7); errs.append(pg.errs); nav(pg, 1)
    ci = pg.evaluate("CHAPTERS[1].quiz.map(q => q.options.findIndex(o=>o.correct))")
    L = pg.evaluate("CHAPTERS[1].quiz.map(q => { const l=q.options.map(o=>o.text.length); return l.indexOf(Math.max(...l)) === q.options.findIndex(o=>o.correct); })")
    check("квиз: верные ответы не все на позиции B и не самые длинные", ci == [0, 2] and not any(L), f"{ci} longest={L}")
    for qi, oi in enumerate(ci): pg.locator(f".quiz-opt[data-qi='{qi}'][data-oi='{oi}']").click(); pg.wait_for_timeout(50)
    check("верные ответы засчитаны", pg.inner_text("#progressLabel").startswith("1 /"), pg.inner_text("#progressLabel"))
    check("нет ошибок страницы", not [e for l in errs for e in l], str([e for l in errs for e in l][:2]))
    br.close()
print(f"\n{sum(res)}/{len(res)} passed")
