exec(open("p3.py").read().split("with sync_playwright")[0])
U9="file:///mnt/user-data/outputs/git-trenazher_15.html"; U8="file:///mnt/user-data/outputs/git-trenazher_8.html"
def c3(pg, t): cmd(pg, "ch3", t); return H(pg, "ch3")
def nlog(h): return h["out"].count("commit ") if h["out"].startswith("commit") else len(h["out"].splitlines())
def flags(pg): return pg.eval_on_selector_all(".mission", "els => els.map(e => e.classList.contains('done'))")
def R(pg, ch="ch3"): return f"STATE.chapters.{ch}.repo"
with sync_playwright() as p:
    br = p.chromium.launch(args=["--no-sandbox"]); errs = []
    print("=== ДО (_8) ===")
    pg = fresh(br, U8); nav(pg, 2)
    for t in ("git log -1", "git log -n 2", "git log HEAD^", "git diff HEAD~2 HEAD", "git status -s"):
        h = c3(pg, t); print(f"  {t}: {h['out'][:60]!r}")
    print("\n=== ПОСЛЕ (_9) ===")
    pg = fresh(br, U9); errs.append(pg.errs); nav(pg, 2)
    # log
    h = c3(pg, "git log -1"); check("log -1: один коммит", h["ok"] and nlog(h) == 1 and "Обо мне" in h["out"])
    h = c3(pg, "git log -n 2"); check("log -n 2: два коммита", nlog(h) == 2)
    h = c3(pg, "git log -2"); check("log -2: два коммита", nlog(h) == 2)
    h = c3(pg, "git log --oneline -2"); check("log --oneline -2: две строки", len(h["out"].splitlines()) == 2, h["out"].replace("\n", "|"))
    check("…💡 говорит про ограничение вывода", "ограничен 2" in (h.get("explain") or ""), h.get("explain", ""))
    h = c3(pg, "git log -n"); check("log -n без числа → not an integer", (not h["ok"]) and "not an integer" in h["out"])
    h = c3(pg, "git log HEAD^"); check("log HEAD^: 2 коммита (без последнего)", nlog(h) == 2 and "Обо мне" not in h["out"])
    h = c3(pg, "git log HEAD~2"); check("log HEAD~2: 1 коммит", nlog(h) == 1 and "Первый" in h["out"])
    h = c3(pg, "git log HEAD~3"); check("log HEAD~3 → fatal ambiguous argument", (not h["ok"]) and "ambiguous argument 'HEAD~3'" in h["out"])
    h = c3(pg, "git log nosuch"); check("log nosuch → fatal ambiguous argument (раньше «история пуста»)", (not h["ok"]) and "ambiguous argument 'nosuch'" in h["out"])
    h = c3(pg, "git log index.html"); check("log index.html: коммиты, менявшие файл (2)", nlog(h) == 2 and "Добавить стили" not in h["out"], h["out"].replace("\n", "|")[:80])
    check("…💡 про файл", "менявшие указанный файл" in (h.get("explain") or ""))
    h = c3(pg, "git log -- style.css"); check("log -- style.css: 1 коммит", nlog(h) == 1 and "стили" in h["out"])
    h = c3(pg, "git log --oneline HEAD~2..HEAD"); check("log HEAD~2..HEAD: 2 коммита", len(h["out"].splitlines()) == 2 and "Первый" not in h["out"], h["out"].replace("\n", "|")[:80])
    check("…💡 про диапазон", "справа от «..»" in (h.get("explain") or ""))
    for fl in ("--graph", "--stat", "-p", "--author=me", "--since=yesterday"):
        h = c3(pg, f"git log {fl}"); check(f"log {fl}: честный отказ, а не молчаливое игнорирование", (not h["ok"]) and "не поддерживает флаг" in h["out"])
    h = c3(pg, "git log master"); check("log master: ветка распознана как ветка", nlog(h) == 3 and "истори" in h["explain"] and "от указанной ветки" in h["explain"])
    # diff
    h = c3(pg, "git diff"); check("diff: только неподготовленное (index.html), пояснение про рабочий↔индекс", "index.html" in h["out"] and "style.css" not in h["out"] and "рабочий каталог ↔ индекс" in h["explain"])
    h = c3(pg, "git diff --staged"); check("diff --staged: style.css", "style.css" in h["out"] and "index.html" not in h["out"] and "индекс ↔ последний коммит" in h["explain"])
    h = c3(pg, "git diff HEAD"); check("diff HEAD: оба файла (подготовленное + нет)", "index.html" in h["out"] and "style.css" in h["out"] and "вместе" in h["explain"])
    h = c3(pg, "git diff HEAD~1"); check("diff HEAD~1: сравнение с прошлым коммитом (index.html показан относительно 'Обо мне'? — до правок)", "index.html" in h["out"] and "footer" in h["out"] and "style.css" in h["out"] and "(файла не было)" not in h["out"].split("style.css")[0] , h["out"][:120].replace("\n", "|"))
    h = c3(pg, "git diff HEAD~2 HEAD"); check("diff A B: два коммита между собой (index.html и style.css)", "style.css" in h["out"] and "(файла не было)" in h["out"] and "footer" not in h["out"] and "один указанный коммит" in h["explain"])
    h = c3(pg, "git diff HEAD~2..HEAD"); check("diff A..B то же самое", "style.css" in h["out"] and "footer" not in h["out"])
    h = c3(pg, "git diff index.html"); check("diff index.html: только этот файл, пояснение не про коммит", "index.html" in h["out"] and "style.css" not in h["out"] and "ограничен указанным файлом" in h["explain"] and "указанный коммит" not in h["explain"], h["explain"])
    h = c3(pg, "git diff --staged index.html"); check("diff --staged index.html: у файла нет подготовленных правок → пусто, пояснение про совпадение", h["out"] == "(изменений нет)" and "Различий нет" in h["explain"])
    h = c3(pg, "git diff -- style.css"); check("diff -- style.css (не подготовлено): нет изменений", h["out"] == "(изменений нет)")
    h = c3(pg, "git diff nosuch"); check("diff nosuch → fatal", (not h["ok"]) and "ambiguous argument 'nosuch'" in h["out"])
    h = c3(pg, "git diff --stat"); check("diff --stat: сводка", h["out"].startswith(" index.html | 2 +-") and "1 file changed" in h["out"], h["out"].replace("\n", "|"))
    h = c3(pg, "git diff --name-only HEAD"); check("diff --name-only HEAD: имена", h["out"].splitlines() == ["index.html", "style.css"], h["out"])
    h = c3(pg, "git diff -w"); check("diff -w → неподдерживаемый флаг", (not h["ok"]) and "не поддерживает" in h["out"])
    h = c3(pg, "git diff --staged HEAD~1 HEAD"); check("diff --staged с двумя коммитами → usage", not h["ok"])
    # untracked
    pg.locator("#newfile-ch3").fill("todo.txt"); pg.locator("[data-fileop=create]").click(); pg.wait_for_timeout(60)
    h = c3(pg, "git diff"); check("diff не показывает неотслеживаемый файл", "todo.txt" not in h["out"])
    h = c3(pg, "git diff HEAD"); check("diff HEAD не показывает неотслеживаемый файл", "todo.txt" not in h["out"])
    # show
    h = c3(pg, "git show"); check("show: последний коммит + его diff", h["ok"] and "Обо мне" in h["out"] and "diff --git a/index.html" in h["out"] and "footer" not in h["out"] and "не меняет" in h["explain"], h["out"][:90].replace("\n", "|"))
    h = c3(pg, "git show HEAD~2"); check("show HEAD~2: корневой коммит, файлы «не было»", "(файла не было)" in h["out"] and "Первый" in h["out"])
    h = c3(pg, "git show nosuch"); check("show nosuch → fatal", not h["ok"])
    # status -s
    h = c3(pg, "git status -s"); check("status -s: краткий формат", h["out"].splitlines() == [" M index.html", "M  style.css", "?? todo.txt"], h["out"].replace("\n", "|"))
    h = c3(pg, "git add index.html"); h = c3(pg, "git status --short"); check("status --short: staged", h["out"].splitlines()[0] == "M  index.html")
    pg.locator("[data-fileop=edit]").first.click(); pg.wait_for_timeout(50); h = c3(pg, "git status -s")
    check("status -s: изменён и после add → MM", "MM index.html" in h["out"], h["out"].replace("\n", "|"))
    h = c3(pg, "git status -sb"); check("status -sb → честный отказ", not h["ok"] and "не поддерживает" in h["out"])
    h = c3(pg, "git blame index.html"); check("blame: настоящая команда, но не поддерживается", "настоящая команда Git" in h["out"])
    h = c3(pg, "git stauts"); check("опечатка → «не является командой git»", "не является командой git" in h["out"])
    # resolveRef
    r = pg.evaluate(f"(()=>{{const r={R(pg)}; const L=r.log(); const id=L[0].id; return [r._resolveRef('HEAD^')===L[1].id, r._resolveRef('HEAD~')===L[1].id, r._resolveRef('HEAD~~')===L[2].id, r._resolveRef('HEAD^^')===L[2].id, r._resolveRef('HEAD~1^')===L[2].id, r._resolveRef('master~1')===L[1].id, r._resolveRef(id.slice(0,5))===id, r._resolveRef('HEAD^2'), r._resolveRef('HEAD~3'), r._resolveRef('HEAD@{{0}}')===id, r._resolveRef('HEAD@{{99}}'), r._resolveRef('abc')]}})()")
    check("_resolveRef: HEAD^, HEAD~, ~~, ^^, ~1^, master~1, короткий хэш, ^2 (нет), ~3 (нет), HEAD@{0}, HEAD@{99}, «abc»", r == [True]*7 + [None, None, True, None, None], str(r))
    # миссии
    pg = fresh(br, U9); errs.append(pg.errs); nav(pg, 2)
    for t in ["git log", "git log --oneline", "git diff", "git diff --staged"]: c3(pg, t)
    check("4 миссии раздела 3 выполняются", all(flags(pg)), str(flags(pg)))
    # пустой репозиторий (раздел 1)
    pg1 = fresh(br, U9); errs.append(pg1.errs); cmd(pg1, "ch1", "git init"); cmd(pg1, "ch1", "git log"); h = H(pg1, "ch1")
    check("git log в пустом репозитории → fatal, как у Git", (not h["ok"]) and "does not have any commits yet" in h["out"], h["out"])
    cmd(pg1, "ch1", "git show"); check("git show в пустом репозитории → fatal", not H(pg1, "ch1")["ok"])
    # reset с новыми ссылками
    pg4 = fresh(br, U9); errs.append(pg4.errs); nav(pg4, 3); before = pg4.evaluate("STATE.chapters.ch4.repo.log().length")
    cmd(pg4, "ch4", "git reset --soft HEAD^"); check("reset --soft HEAD^ работает (HEAD^ теперь поддерживается)", pg4.evaluate("STATE.chapters.ch4.repo.log().length") == before - 1)
    # теория / квиз
    pg = fresh(br, U9); errs.append(pg.errs); nav(pg, 2)
    th = pg.inner_text(".theory-block")
    check("теория раздела 3: без «кто, когда…», есть про -3, файл, HEAD, show", "кто, когда" not in th and "git show" in th and "-3" in th and "git diff HEAD" in th)
    check("рамка про отличия от настоящего Git есть", "Чем тренажёр отличается" in pg.inner_text("#content") and "нет автора и даты" in pg.inner_text("#content"))
    ci = pg.evaluate("CHAPTERS[2].quiz.map(q => q.options.findIndex(o=>o.correct))")
    L = pg.evaluate("CHAPTERS[2].quiz.map(q => { const l=q.options.map(o=>o.text.length); return [l.indexOf(Math.max(...l)) === q.options.findIndex(o=>o.correct), l]; })")
    check("квиз: верные ответы на позициях D и A, не самые длинные", ci == [3, 0] and not any(x[0] for x in L), f"{ci} {L}")
    for qi, oi in enumerate(ci): pg.locator(f".quiz-opt[data-qi='{qi}'][data-oi='{oi}']").click(); pg.wait_for_timeout(50)
    check("верные ответы засчитаны", pg.inner_text("#progressLabel").startswith("1 /"))
    check("нет ошибок страницы", not [e for l in errs for e in l], str([e for l in errs for e in l][:2]))
    br.close()
print(f"\n{sum(res)}/{len(res)} passed")
